{{- if and (eq .Values.externalDns.provider "cloudflare") .Values.externalDns.cloudflare.apiToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-cloudflare
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  cloudflare_api_token: {{ .Values.externalDns.cloudflare.apiToken | quote }}
{{- end }}
