#ENC[AES256_GCM,data:mTjN5QCke5Bjc3BPr3bvIB6Z5RTuZdhvOqvRkpKxLiyNA1M46aZaI6pXHjVFmEVQn+iPJKjOPvdTfehBmVV5cuN4TsUg8fLx,iv:I7PgNgTFHkwebGW+1UvEroONdWewgNNJMyKHop3whQ0=,tag:U2mk4K5G40vxi1b7mfbZVw==,type:comment]
#ENC[AES256_GCM,data:eF3SHMD4/Io/XaAOunmOPzr35J5aH9yxXHCg30yxLFJZkhIu6+PHIBS8D9Xt3WfbTUI+GBD6gyaUd4+bHlI=,iv:aPRHbXju8TQXoXSL0RzFmJBs2TE9Yf0axvnUR8PNt/c=,tag:Ku4jeVtxMsdnIkWUWPjK4g==,type:comment]
#ENC[AES256_GCM,data:bENb/dwiU0jZL8UdJW8ChMiWuOGAHkJgs0Y9wZTlricTfVdofHa3WjqL9G/R1YUOX+3awYJJrhd9vFA=,iv:iJZdygRPrbOI/V63RQseb78x9gO4iy9G+0RzxHloL3Q=,tag:ExFwiz4BDTRTtrp8QQgWKg==,type:comment]
apiVersion: ENC[AES256_GCM,data:iFU=,iv:b+S0++TXba2crSB+S15HXKN1ZwBclo+Sa6THBAexHD0=,tag:xMveaAZEUmu6HLZ0o+WLzw==,type:str]
kind: ENC[AES256_GCM,data:CovZug29,iv:7GmmQVdhZotM0mfiwtPWrN0VnHwStJwskFf6Mx89ZUA=,tag:GaOD7hRTi89d7gVu6wlxZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MzW83pZGDTVq/nLNMg==,iv:jqFXw1rdUSFQaqN3NpXEq27b++fC762Q6NfKsUxkhXM=,tag:3Q7ye63XGgfSpqjmt2TtNQ==,type:str]
    namespace: ENC[AES256_GCM,data:85nRwCbtCVQ=,iv:MZ+6UTAdBGaiF5bdqTgBeRQiNWyr//j4LZLsXbwot8s=,tag:pdb9rhaEWzNRkyKuuQIWwQ==,type:str]
type: ENC[AES256_GCM,data:+vHIiaO/,iv:L18FVJiJytyNTvG8pvQBXdWhi0PF7a+JFF003z9LP7Y=,tag:abgN2OV/MQ6cnhC1t3MyEA==,type:str]
stringData:
    clientID: ENC[AES256_GCM,data:tlD3NTDgNCA=,iv:HA8OV0fRE4U6ewoior1WVGVaV6pz3Kqzi/vvfMfdMZ4=,tag:XKrL/WfDtd1Qm5EASwzh6Q==,type:str]
    clientSecret: ENC[AES256_GCM,data:BUUIKHPD0xUgxuN/tk0H1aY7yBia5Z6GI4SI+Ehl9Erxh3zO9T9RnA==,iv:8H+YLtFq0cqiQYAdW0MfpF8uH6mKTQtQgOfcVkuUA2A=,tag:c5Ckplk2HwjAyR/HpWaPPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b2dFWjFRN1hLUmFtbjh2
            UnVIc0xtVVZMWnFvZDNkbzN0Z2toNlV2K2p3CnlpV1lTMU5VSW1LbzlJVjhMUmlk
            MkR3aWZYZU9oR2V2U3FmMi9Ucjc4eTgKLS0tIDJiejJlaGs0ZW5IYzA0Wk5MQ3pC
            WG9xR0JzVFFqYm5PYjFOOGs2SExYaWMKvLMuxARVge568QQeGobwZla3BOrzu6y9
            5oapWQOXMy78lsqjBDY9LpdeLivMme2chLZoH4mQPX+pBWbogrkocA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lf53pymuyys7tl4t89v27q0dmfkdqg0mxme7z7cqh2vefx8naanqwvlhtx
    lastmodified: "2026-05-15T08:56:10Z"
    mac: ENC[AES256_GCM,data:vUq2VPzfQ3Xv4U5vTBD4L3ZQtfAvz+qdThdGO3bPcYgboLS8RBmyRjWNEMWe4EwU1XMIE1+VqkGcsrFkTPApzI4CVzLKOmFQvm0/Wekq153+UVvaOjn4cJ4dpPlyDQcEpK3kXDm8gEUMwIOgJ9RMjAYX6jHe9I6mSJxFW+8n/1E=,iv:7WRvjpYkDC4EAAM2N0xx4/lpFLiDFmuyXy/ZpoFelSk=,tag:lfpAyUQ4tzCfalJ+uAaxqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
