apiVersion: ENC[AES256_GCM,data:Wmk=,iv:cHgrTaYx3ueaFdooHxngkgF/FiPdIvXmxn+qFi1ORO8=,tag:DnMo5KUdo+fuKPDPbQIYsw==,type:str]
kind: ENC[AES256_GCM,data:ovzM+7j2,iv:FucGWhiUZYKcLckJNSb2k7cVsdEsLUXIoGQRfFqoP+I=,tag:Y6ayzTx0XXHYLX6DPJEbYw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W33gB3pMACoj7WdZDw==,iv:hB14q/JNa53bdM3/2Wwg7ubWPhcXZUUA/qb20/MruwM=,tag:prXxMYKngmjO69jl1Gjd4Q==,type:str]
    namespace: ENC[AES256_GCM,data:X+eQnszL27I=,iv:V6c+/FBywaVEXPOsv8vcGHaiF+hqfJmMBJg1nO61TO4=,tag:PyChGVwsMLQ7l/5lWujAmg==,type:str]
type: ENC[AES256_GCM,data:qTI2UceM,iv:eArnGa5T6TAPkmsIiST35lmhZAytV9IKiz1tUhXGk6Q=,tag:3sS+ecZhjd3R2RLsNbhIdQ==,type:str]
stringData:
    clientID: ENC[AES256_GCM,data:FF8RUfc7AHc=,iv:v51D0Bw2BrSycUJjmbYxnRYeREZDUKAFpo5foLUSMjk=,tag:f4NZHHGHIG6IhvyOz+urug==,type:str]
    clientSecret: ENC[AES256_GCM,data:639yKlqwxrSftKF56/r/zR94Y0zP613TYW1DmOyTHKqZob6gXBAvkg==,iv:tUsPuGYsbg3GyeW7wOx5d2m3Pxq1uo0M8e3NmbddLn8=,tag:k1UhILo6hllGPHKWS1DPUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSU1yN3RFR1JiamJTUzMv
            RTJDZHZGb3ZOZzdmM0U5YXZhZHBKWnM0ZTFRCitJRnY0U0Fzb1JyY3JUVDVCVVpx
            OUtmWXpQREovVWhrSnY2bkpnZCt4NTAKLS0tIFQ3bTRSTnJ6L2Y2eExnZnlXT2Fx
            SmNRWk4zSmFURE1WbndQY3ZQTEVDR2cKGEn12mIv0caWQeOjxZcLs+azgx670yqq
            72e+BTf4W61c/SkwD6MMC1n8Le03p+msMhHjoLAZW4I9L/eVpB1nwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xgfvsdpafpfg8h459ulakcjq4lz7jwhy5qtfmphke0kukkd7xyusu83ajs
    lastmodified: "2026-05-17T12:39:01Z"
    mac: ENC[AES256_GCM,data:AOnZVRRUmtm66G20d+x2AosGDhJRs2ggLYWmT5+C+MaA2nsGKOLALHJLFr0MnktMiJwH2cixgxJDFDNHLSB2M7ZXqfYhMwd9J7Lq515JSBDLBcYZhS0U2SvlOJYb8L0JMcP8SGVbN+RS4YNMczllqpChr6LDl5M5dyBxAvMe81E=,iv:5nyCtbOR0g5rHHP+mlpEjhfnWq5DtWA4I32jqQdcs/s=,tag:u7hTeDaJ8Mjg0PB7GkCwQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
