apiVersion: ENC[AES256_GCM,data:h3g=,iv:PBt7o3MicN4Jbdzmr8NghuOhf//KmN6V3IsfrSca0xk=,tag:VbSiLPsk6MigUXh6EbMQzw==,type:str]
kind: ENC[AES256_GCM,data:C+8c3jT7,iv:MH0te0CCawa+ZpLewx/VZL++p/TVEnoGEX6uyPsb5cE=,tag:bpELtZ4pZ+YiwIM25aPJMw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gj6o5iAFZA8Gssnwyg==,iv:pMGjbrlyteRttUUQgC3/dpgwuuZV+74NPUC8Jw0pyMw=,tag:8wYnscB+9tswtws1VgudBw==,type:str]
    namespace: ENC[AES256_GCM,data:1Jc5L6Ymoo8=,iv:YZBIK0mnN5HxYzlLRUIoXBQ8QpufFr+a7wFOTkld538=,tag:kfjhKVBbU5Jz+4/rPDENOQ==,type:str]
type: ENC[AES256_GCM,data:CiNAKWGv,iv:vx0nCIcq6g2Vj2OqdRqGf9XIFa5SXt/BZ60TE8KhxrQ=,tag:QqW2FT7Q1Idv2TXGK+YTuQ==,type:str]
stringData:
    clientID: ENC[AES256_GCM,data:PIH4ts1qE6Q=,iv:I7r/cJ+L7DrrjP9Lr0+YggkIbQfu9qwWo+0PULPiXHk=,tag:aAo+FfnRKSFqhp5bWB2M7g==,type:str]
    clientSecret: ENC[AES256_GCM,data:xQAYKIGzU22qS5HLCBW2zl6Xm/KdifGYVlHmI5zQxMV0yW6SoH1Oiw==,iv:kl+WjCLPwcRjqc7y4gK7mfA4mK52ZZLKUkIisxYrphI=,tag:g6ApYHm13beqCi3LMOENiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU0lrazVmeFM1OTNQV3N2
            c0p1KzAxRWJITFY1K2dZQ3NVdzV0bGlJeldFCmJmai9JR2tBTXl3QWZ4UEk5R1F3
            VkxzMElrU1B2SFhqWS9BUzFSbnRoMlEKLS0tIDBxWHBKcXJhVXFvc2tBUExkT2s1
            U2psTHNpci9ZTmhDM0ptcmxtRlIxSEkKu4/twDpQKXB8gGVPzPdH6qyFHlqEcgLE
            PrgTt6CPDcRMWlkmnF5U3g+V8qeclkr5GAbZ7Pz1vplV8HuInkDpcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q46kuuw2yec6r9n2vz6gezhnvf3fz6df9x0h6gtqpjylnfx00fcq2khyq9
    lastmodified: "2026-06-06T17:15:56Z"
    mac: ENC[AES256_GCM,data:J2Tk86U58jhLQhV4vOkq9ixAF4OvNTwjNyc5EZmQI73u8l2hsTMZwTFfm5uuYaowbJyBtFM9lkjKeYVcpxfe8IMT1mU2tOLaITFYTHHF4uTLXi8UNf+A4yRhRof7yPKoSoaF9aHWtKo0Cyv1K9M8nw4AIiziNc4F8cqOWVmu+is=,iv:3NO1mrmITQAAf+MX4/b+9iV23IXd1qkhtVaRhCMOIhc=,tag:0x9H5pMZXZdKybGxRVgW4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
