---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - provisioner-configmap.yaml
  - provision-job.yaml
  - hubble-ingress.yaml
  - auth-proxy-configmap.yaml
  - auth-proxy-deployment.yaml
