apiVersion: ENC[AES256_GCM,data:UWU=,iv:IOwIbwzFDV4cCYp5ZeW5czdAqPs35yPfNFPKWXhp76E=,tag:2+LTZs1RvrMSrTYetZU76A==,type:str]
kind: ENC[AES256_GCM,data:U2bWLuRh,iv:rnTJE6Z7DVxrA9x760cp6o/AMMQcXIPXSr9dK2D08SU=,tag:z6CyN1L1pAIGTJ09JpZdBQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S4TphilXz7r/9jHukifQ3MsXaPU=,iv:EX9phdfIS+QnOtrYBELXz3JabTTaDutjR/QZd2CYlRA=,tag:GaaKEk11isTxR08S33+Epw==,type:str]
    namespace: ENC[AES256_GCM,data:FY7cXmHYURB+nL+f,iv:9i9DY/0JIyvm1PgZmEfLgm9PCI7UfU3TE4apqRjExHg=,tag:lIWo2ApaOrAMyCWgy+N2WQ==,type:str]
type: ENC[AES256_GCM,data:VRHXhE8R,iv:R5glG0AqFmi0OmXqTJ12z8CEWYjGhSGCBdvPsBJD+pA=,tag:VgddsaVbi3uWNJ046QzQig==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:fqLoDmAXRi1MXRYQ0NvXlqfRLXUxH4f2RFIU0x1ns2uKataNRR8crodr7uFIzvlKNjyq3Ds=,iv:mHfL8mM6HxuZPJn7E3A0viPIUNCaHEuTTAiPVbUeh1Q=,tag:Ad+ssQ60KjANxYDT5XxwtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZDM2UndZTlQ1N1ptUUJV
            WDd0OUJUT0pEVmF1OVlGMjRSazl4N0JiZXpBCjR6UlM1Y1lqcHJLcGtrbExvbmFG
            VVRmY0Izb2tzWktrbU9tWkc3L0ZUcmsKLS0tIGlycDZzSEkyejUwaGZmakYvcXdR
            bGJYdng2Wng5b2ZvbXVRQ1NXNVoxeHcKd182JySqhqB+bCGFzCveMFeXCIzoozox
            XDEh6p+8mH+dCJIUl2+RHPybfHtp2myMWxqSfkm/UoLp7JUC8Ozeeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xgfvsdpafpfg8h459ulakcjq4lz7jwhy5qtfmphke0kukkd7xyusu83ajs
    lastmodified: "2026-05-17T12:33:05Z"
    mac: ENC[AES256_GCM,data:uK7/6sGUIHV0BMEFON59eKSXu/pFG7PMOHU1/Dy5+ozwOSeckD3sj4S6MHJr9u8MHVKkcKH4aBhrL9RBd9moaeL0YnBLi+O5mBdeIlrXll8t1+pJjhOPrvAu2AaFCfxwUcX35deiD//nDh553u2dqpKpKxxrnTADeLIRRQqIEtc=,iv:er8XvGUHdYqxmfCVIYAAmhoCJezZtiHF2Q9LSJlGVbM=,tag:JQ6rZ2O/BQzgIIYDl9ZkPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
