apiVersion: ENC[AES256_GCM,data:134=,iv:jITHkGEqKlRR5upJWflZVm1rlxjIUbIKswW+TohHJ1I=,tag:bAOTIvBZDDVKt0DzEFEYBQ==,type:str]
kind: ENC[AES256_GCM,data:0c3YL3wC,iv:tToNc0UQ4db6x+jVzTJRsXuMtGp4iD9ZBB6mctpMBCs=,tag:kcsTCkT6SlN59TVz65YGRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OEL/KSgG3DitRtSmp2oGx615JE0=,iv:RtCYMJtlSDnM+rJcyMVZgW0+vx7auQ475sqA35S9cE0=,tag:fKgxTyRZluBwtow0zCl7Eg==,type:str]
    namespace: ENC[AES256_GCM,data:i1VO3g7NKARjJTTu,iv:D9ENVQLoxXeguLt4NiZS9DGCpZVvzWhAqf029wPhVHk=,tag:fgzV0ZuY+PdhBHbTPN8+6w==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:mOPPfls4NDMi3X+A3+yZBAF/vl2w8UGgRaaG4xHB65ufg1HfK1gHjvhCwCkfq72uuwyOtRM=,iv:mCsjqWJxUrnkGknoHp0i7Y6IAv27ovR3Hht73pU/Q8Q=,tag:Eshhwc2cRyrATcXOAMS3+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL2ZzWDJsVW5seFlnSmNR
            UGdrUnFaYStFT0pXYldXUEJweXpVT3k3eTJVCnNrQUxEL2pGZDhvcDVMa2FDL3c4
            NU1sZVBEajc4NEZ5M3lEYXJwMnF5dHcKLS0tIHJjeHp1RDNodjk2MVBrTTFRbnZr
            aktTQ25yc05UblhuVDhSUC8yR2hTelUKa+DH9z+iKYgmeDnFBKUTqtCS8q2zey7I
            wGPMEGzv6eoNfX23wTeCHyAlrEPygf2jnm4xQYlqxcRXZjs8jZYXag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1myvefml2hyy2ynfgj5vjlmlssqf2r0rz0g9qnk33mrqfmcmvjq6shq46x0
    lastmodified: "2026-05-15T20:45:13Z"
    mac: ENC[AES256_GCM,data:45UjG2/dTP/AYge/MPR+7Dw+ff0bB9k0dnEVSOuibz9wcpM1Etwz4jKkJRVXDk2di6eLe3RYAKQE6R49esokzgMNn3eqDBYsHd57IKZEFEEwX2Ks1Y0jeBjkDzo71pXL+pVTxlvho++sVJ+1HrM4AfzwsZ5LZ/YX7zj6xXdumgQ=,iv:U5Lk4DYVerLLLdwNuDJ+pa4eXigyjj4nq4jqKJB6mqg=,tag:MpEtsxPnUpcqH5p+LjGOEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
