apiVersion: ENC[AES256_GCM,data:/OA=,iv:lv/FeRsA2ajLerOgmm61yRg/fIGLPmjiEEAkndg5fRI=,tag:FTiEqjYSNnvSNvLHNPk++A==,type:str]
kind: ENC[AES256_GCM,data:RYk0rXl/,iv:eA0Uc5uwpkgY9J7fyl8kBeVJdtN8wYEBWQEZ/jDW/Zc=,tag:uQ/USYQlyCgD+h7b97c5vw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:u6Nx6J798RhYpq64Z+nogrUK8aQ=,iv:UL6FfMcW5mSyZwTvT+CMqUxOEfm52E9VUJUnJQw7dvA=,tag:D11AxMU1ZtLGRisQjXk9RA==,type:str]
    namespace: ENC[AES256_GCM,data:7GyrCGVf0IFIhlrX,iv:UEwZV+hGVjKSV4AsWpxi1NKkidsZp8qev92Fnd4f8tg=,tag:E0eqnOlUVrXVLN9DpCn//Q==,type:str]
type: ENC[AES256_GCM,data:Rudqsllm,iv:7jnQaJOYKURHaP/rWyej/qVC3Y+/q4SNzIV2IyKd0cc=,tag:FUM/L1/mx7jeCyucQAQYpg==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:VWvZRyf2AxYK+luKMxWjNUl4/c3R0XZiPE+oq666HKTLlW+ibgavM8Vqqtke8m2uJ3Okdq8=,iv:6Mm0WvWjAJauDUdfOUHqJqfxMKY8h77HrHL3jZC+UUE=,tag:qec9n0nNpPxHGvnLfJ2VNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd1RVTCsvbHRKbjVCZFBa
            S25XMzNxWXJObVhLUXVzRDFxbGpncHFWQUVZCmFjalNCSG9tb0w2RkhCSzZHRldS
            S0FMeitHSjJydHk3UStIT2lvcWRiZUEKLS0tIENoYzAxRzNudVl2TURTMk0zdzZs
            eWlnMkdZMW5TK2I1WkZKQUY3VkpiY0UKcaQ6DrZsbrtX2Bp09AqIHxbw15jjIPBg
            2ZoTHbzN78Vi48dasTRDmTyRvL81Xkgee08Jw5jDOy6VKs2o8KGS3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q46kuuw2yec6r9n2vz6gezhnvf3fz6df9x0h6gtqpjylnfx00fcq2khyq9
    lastmodified: "2026-06-06T17:15:56Z"
    mac: ENC[AES256_GCM,data:Qea2bcfyiAYOkc6R13+EIY48YXV1rUlntMePSDKsR3UlsMK1FJfS9F2aHGwPXjX/SjdCA1rr9CpqRBhLUQ+WTtQt0D48zeYX5hzKtGUQ0+Me4/2HxKeMGEV/uplBB2/LyCEeOhDGZSDTBesGiYbB6OVLDOsGPUjCNNzPmEx4wpE=,iv:Rtz3FoFu41PmQykAmo/jD6E0kogObX89zbw6tMGx+tE=,tag:NpfuTGHS4P+I6Qik21b7hQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
