apiVersion: ENC[AES256_GCM,data:Fsc=,iv:zGNNVX5NCS0rZdVHQ48Lo/Rtl/zXkISs3pE7h3/r3yE=,tag:J9xp9erg7IBX28QsO7eO1A==,type:str]
kind: ENC[AES256_GCM,data:PK1WzrZs,iv:1CM2c7TzchEDz87ZGmGOdYrytTb+S8hkMobZ/NQnLqk=,tag:esqY4i3Q4W9+QzsspHSF/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SckbJtS7zjpEaQzMW4UzrJZrOM4=,iv:G3mqtguPAoSB7qLkEsC16wnHa+ncTKngu/oLN5UXiR4=,tag:YEj5V/gJPMJB7jGsdQ28fw==,type:str]
    namespace: ENC[AES256_GCM,data:Au8exV9XGouauJKs,iv:Egy+lQucbnMXZIxqeV25eHevXOnyas1F2Os6aBC+9BA=,tag:TQ8EEh+VGUSRoiPhz2faNQ==,type:str]
type: ENC[AES256_GCM,data:cwaIDCz+,iv:s/CyKx7OlsUm1QgboMyNBk4BMuXAsSIHnZToj9gmRXE=,tag:5npYPGkaA7vLhVpRmWpjHw==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:6n9Q/YFGpMnWCqCk143KeL9yCrYOqwGiawbGijasLN4LACGhJneYsXsFfLlNI4mZr1fIW4M=,iv:osLmHEeZZSU0ctqxw+qxHKz6+0ctGahq+dCzBGBKwWw=,tag:IgQBvcNf8iaZsZul32Y9pA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d0J6NG9ObkQ4QWcxYnY2
            bnYwN2JVZkFxYjNMbTRVbzMxOUkxSEJSWGljClNFRnR5MHk4bGRBUU1GTVM3VlhU
            RDcybDZHL1JIU1ZMTnBsTVhHaktaTTQKLS0tIDR1cmlwNkVuaC9zV2krVG5nVjVI
            ZkNVL1dyNHAvTkVGY1o4QzRkOU9sdTgK1jbY+3oNPldtRs3DvHseYEkpu7tsmHE+
            n/jJdnZZ/T1az/v4Eavpf3t63KgOrkDKg+1zdjxTFI3RrZ94eEzrBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xgfvsdpafpfg8h459ulakcjq4lz7jwhy5qtfmphke0kukkd7xyusu83ajs
    lastmodified: "2026-05-17T12:39:01Z"
    mac: ENC[AES256_GCM,data:VaelPbJWfUtQQ/rMglFqqrMbs7oEMk7OT7F2fvriWTcnO5lqQx3mvwWoBK1iZeWqCzFAoy7ZmGxi9vc37TUkmOlrdBsCB30ggzVOABQyGUyceX8h+LOm/x+qkyMRkWfog9BaQClau4AK88fTX2amCImTinpqmhChn7ULGlXBOJE=,iv:PoMSckiemWlLdBsNgE53zcONjj4MCt2jjje6htY1mNQ=,tag:VbEFPIZSQoyPvFV17Wqsug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
