apiVersion: ENC[AES256_GCM,data:x/Q=,iv:aEsN/0zYJ6tu/hldPnW4mVR3dusdAcGLfPnicDo/9Ew=,tag:/vq25XIWEwardlIcMcy3iA==,type:str]
kind: ENC[AES256_GCM,data:SvhJuP4p,iv:reu8CbMxPHlMfCvvat4o6uuHvpk9rSF20EQw0wmJYqw=,tag:m06iwl7MoPVeGObC2zrz7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Hqp/c0zcXuo4LAkmYhl4U4NFWK4=,iv:Sk1SD24CG4e9Jd+Uz+BmYL1Xysu4ntCV49NFqfUVL7s=,tag:S9rkhhqUwzVAY/kouyZJng==,type:str]
    namespace: ENC[AES256_GCM,data:Qm0h0dPAEr+Opso/,iv:LMWZuyynm2BRvYDpG8OnphrZsxl1/Mh12l302AIZbQ4=,tag:phY3gZilXzuizjRLnsXv2w==,type:str]
type: ENC[AES256_GCM,data:nyJStM5P,iv:LokjqlQBFvVEaynWz7NZAqBf5e5uU0Og4sfDlk5VD4U=,tag:tyfR1VAu91a11JpyeGzsSA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:lyPmYA/Ef3wgefNU8uin1YeNKX4KmaHZ9ywAEGhl/j6u/8qFzQoWRPUduTlQR04qlChRFY8=,iv:ysW9kxLFyxrb9A8Sd/QelD9EmZq0nNIwYligNhlRazM=,tag:AlfTTpicaojsgn1S3mcazQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVzR3dnhHMzlPQytFQU4v
            VURlOEF5Qkt1ODhZMzBONWNCZWdEdVYyQTFzCjYxRS8vN013TjRmcStkR3p2bzg1
            QUFRWC9qdENFUFM2SlMzeDE5UHl5T0UKLS0tIC9lZ1ZYM203c3ozcjZhbFc2UndP
            WnVMQUVQZE1XWjJQbXpIQ1RaNk0rSTQKYyD/rOcojhIvpHru24ALHLSZ8LK7rFJW
            LAdjaRvVBA8LRsCZf0d1zz/lPhqMyn9AM4p9Mwdp8F4oet+f2jtKTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xgfvsdpafpfg8h459ulakcjq4lz7jwhy5qtfmphke0kukkd7xyusu83ajs
    lastmodified: "2026-05-17T12:26:40Z"
    mac: ENC[AES256_GCM,data:/sdQBTVq0eq4xfVmWt3iqsVER0huk6tvUTr2c8qbPj5N48BJRY7U2XbY2Q/zRvoseJM8zq/mSucvNuIkLWZTcYLLvtiMK2pwgJzuINFCep3urz7pWQ0WH2uHqyz0ZtXZYzECS1cr/yVb7seMxe7Jv4LfSlt2qEqvEkSn6hlhAs8=,iv:zdGYwB0+2DML648KlNSFJqM1588PxKsT1FRo6mqmsLQ=,tag:3xY1p14aPBTQ40M/s+qmQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
