apiVersion: ENC[AES256_GCM,data:PnU=,iv:u6DP43Sar2ZUUz/dEb+uWLHQ2LhhAJeHxHjHELCjp7Q=,tag:MHOqYH5qpi0EF+KQgU8GKg==,type:str]
kind: ENC[AES256_GCM,data:+i28cHZt,iv:H7JZi+EicxLqgcOuXVgL15zrWrOT7iKKHisjaqwwHu8=,tag:er8TToos+nJeqUk2n4jIdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wM6o79oSHxmmXOqMwSnDZkxB9Wo=,iv:QguW2BY+TFfsOkQaWDcsYo64x6S1Z5zKUlMWgmpLSiw=,tag:fvFOfSokDJPzWdwVlJWIOQ==,type:str]
    namespace: ENC[AES256_GCM,data:wu8D+4aMJxtyK/pt,iv:CIXUVeF4mqD1xUeMXWvv0t7TyDdH9ZcIvV+nW0OM5Qg=,tag:U23Cdq+SoMz0gAjuDN3BXw==,type:str]
type: ENC[AES256_GCM,data:YOk3yyXu,iv:kvRtboL7HS6ezvtPNRA2kUMN9Wx6PbEJ3EreKHoY9jw=,tag:/veWn/mpJJhqswUR4pauKw==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:EoHcz5Qhjhd7E1qbJO8uUHO3Tkh8Wcm8vXtCabSxcohv//fYd1R/MGeOmEAN2jLgYY5OncM=,iv:z9q69Tb/YWIHY6bclapBVdAAiDFhKr1Npuh1MUegI30=,tag:9jF6OLbCza0zofNpuuK7+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMmw2b2crSnM0QW9jMnlM
            ZG5BV0ttUHR0VmFQWkpIbXJTUy80UUJVS1hNCnVtZ1Zzc2kyQUhPN25HdG9XS0dK
            VjZ0SkgrU085djhSTEY0b3QvNlR3YU0KLS0tIHJLeXpiVzY3TE5yODF3aFFQZ3lv
            M0VaRGpjeUI2UG5VQzFaLzV1UjNrSFUKUoFytGE+ZU1mz/HxEhObHDSbuWpTfE2b
            VC8wZwOUVcOhqjAlSIRVBz47Mqdn7H59F0mUZSdHFIZaM5N/l6oLgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xgfvsdpafpfg8h459ulakcjq4lz7jwhy5qtfmphke0kukkd7xyusu83ajs
    lastmodified: "2026-05-17T12:33:05Z"
    mac: ENC[AES256_GCM,data:a4SmMhibR9DBF3L5DZXhNx+Wya1mdj9xIWNo28neArCz9gEMWhf+vv+vZnX5YLpKvN2d3TmwbNZ9eewvI2Q3uVfggRd41X9gr5jVddpIz990sqm5kUm2fxq5KNocldklN6jIK3/T1549yLYfWu1BjG4aRyuPAECJc878RS5Qxt8=,iv:1wvOLpp1lcZd1Y9cfnFxM82nesQb5AgrUwy+UGi0HJw=,tag:S2RhW0gi+Wog4Ngn0Z27vA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
