apiVersion: v2
name: authentik
description: A Helm chart for Authentik - Standalone OIDC Identity Provider
type: application
version: 0.2.0
appVersion: "2023.10.5"
dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "18.6.1"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
