replicaCount: 1

image:
  repository: ghcr.io/goauthentik/server
  tag: "2023.10.5"
  pullPolicy: IfNotPresent

worker:
  replicaCount: 1

service:
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer for external access
  port: 9000
  annotations:
    # Use Cilium's LoadBalancer with external access
    service.cilium.io/global: "true"
    service.cilium.io/shared: "true"
    # Enable domain-based routing
    external-dns.alpha.kubernetes.io/hostname: "authentik.noah-infra.com"
    # Configure load balancing algorithm
    service.cilium.io/lb-algorithm: "round_robin"

ingress:
  enabled: false  # Disable traditional ingress, use LoadBalancer instead
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
    - host: authentik.noah-infra.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: authentik-tls
      hosts:
        - authentik.noah-infra.com

authentik:
  secretKey: "" # Will be auto-generated if not set
  errorReporting:
    enabled: false
  logLevel: info
  email:
    host: smtp.noah-infra.com
    port: 587
    username: ""
    password: ""
    useTls: true
    useSSL: false
    from: authentik@noah-infra.com
  
  # Samba 4 LDAP Integration - Enhanced for Cilium networking
  ldap:
    enabled: true
    baseDn: "dc=noah-infra,dc=com"
    bindDn: "cn=Administrator,cn=Users,dc=noah-infra,dc=com"
    bindPassword: ""
    serverUri: "ldap://samba4.identity.svc.cluster.local:389"
    startTls: false
    # Connection pool settings for better performance
    connectionTimeout: 30
    searchTimeout: 30
    # Enable connection pooling
    poolSize: 5
    # Retry settings for network resilience
    retryAttempts: 3
    retryDelay: 5
    
  outposts:
    ldap:
      enabled: false
      replicaCount: 1

postgresql:
  enabled: true
  auth:
    username: authentik
    password: authentik
    database: authentik
  primary:
    persistence:
      enabled: true
      size: 8Gi

redis:
  enabled: true
  auth:
    enabled: true
    password: authentik
  master:
    persistence:
      enabled: true
      size: 2Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
