apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cilium.ssoConfigName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cilium.labels" . | nindent 4 }}
data:
  oidc-config.yaml: |
    issuer: "https://auth.noah-infra.com/application/o/cilium/"
    client_id: cilium
    usernameClaim: preferred_username
    groupsClaim: groups
    requiredClaims:
      - name: groups
        value: cilium-admins
