apiVersion: ENC[AES256_GCM,data:uaw=,iv:ydqPAf9LDGmjpi0KFpL/c+MRaypx8e7nIKbT/sU2REA=,tag:FNnWxKJhutXdJgrQHwAqlg==,type:str]
kind: ENC[AES256_GCM,data:jeP627zm,iv:RKE/DBVDtTBoaAOr56MZXkusZJVKT72dzCU1rxDOQk8=,tag:pcm0rLiCtX9OZMOF6ms0gg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:N1nxEeJwMLTiDqAv+5WLQw==,iv:hOwCL/CIwLXQzTXmsESQacodd9kSdGaF0yGasT9Gy9E=,tag:oOtegomR3wuMfrQnlTpTjg==,type:str]
    namespace: ENC[AES256_GCM,data:oWPC1H0jmf0n,iv:ZniHTPrlnqHYIm8nISCshKRgAu+w6TGZC+O5zGVuAB4=,tag:Zv3qE+tKU9L1dBwjg/hkIw==,type:str]
type: ENC[AES256_GCM,data:SaSlO2sk,iv:8PMphKdiQ+R6YQp5V6ZBbJeZNrvNJCtRQsDIwYd3loM=,tag:8Q2xg97UgIlJqi6UyLLRTg==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:IJhhGitT7aBAgzo+nqBKRpQFtE76RIk/qyk6pc0XXZGszxlIuxViYFu8FOQta2jfrqO+CcdW5Fdgj7yBNav2T8vJu1KzUFRmeCoaJGZJY9H3GtHnZbrNAf2IRR8b+1wvH5/z4LZ+uoQi/0MIKvrZvYrpFFvsQlBcA06/opQCUcDig6Ji7rdcR4qAN2iBjIAV+FmnwJexyFukz4XGCqVdiN8QcCfdMPoeBdAOxM0K3ZX5B9PjtxzuUU3XCEKPzdSzwq88dr2g79opfjWzyhDSOVt/nlS6rkxGLoMp9v3gOso7hNQQ7e8uPn2FzaW9kLpMJyvKWcwpbHaGIMQX+6ONpeTg+/waBVG4444KG+NIBlm7gMFKRJN0ZS/eKC6sOFBVk+9hPsSAWhvdo6WwXg7r3Nd9Ca8MiIxKIzi2T6s7fYHRuEJup3Z5Pz+C/AyOqrmfnJsdyCEx6PYMFcq5UCF6mafBZr11QL63rQ4DlGgnnZA8LXqZ4l3IIsgmtL6+qPGk7iAOT1B5wmVetSl1tOitVO579EPQXzE0btY13Gj4gpJY0rqc+s3fgQNf,iv:OGlFRHfXD6Jx6n8U9T4zafeWs6O0OgDaPKLga0LYLhc=,tag:vIYvtNtUVcyXSAagWtoDoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVk9kV3M1ZEo2UTNBMGNs
            T29ReVBUd1hibGhXd2tzbXdVK2NQNGgwc1NzCllGUkxSS1VycUUrekVXMVU0OWFQ
            VExEN2x6cmVEdEYxRVRJQWdVTFkyMEkKLS0tIEtBMWt6MDdGWVlTV0xmRHAxc1V2
            dXg3WEttSWVsR0xzSExLNURUU0Y1R2cKJQcaNudAJpLp/m3UjlU9XdulmHKrX3ku
            wA3aHbCdwH+Lxr6Qg9xPe6g2wPXZJKXHgH6cAODkuMoXAaeeo612WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q46kuuw2yec6r9n2vz6gezhnvf3fz6df9x0h6gtqpjylnfx00fcq2khyq9
    lastmodified: "2026-06-06T17:15:56Z"
    mac: ENC[AES256_GCM,data:vBX1cO6iT3rh3CMzkouTcvx7bEkHjcv8oR1rKmUTPHrd8b/CXy/lYOg7zIwbavHwXsvJM8vAxetl83vJYdM1qc1lOmMNTdb94BF2r1nYl1mueprFZokggYFKyny9DE4IOnIDkjA2o8dndlBhmLFCqaoMiBg0rZZ72SvBrNxHFxY=,iv:z0wOedQ7D3TvMWqk7wCFm/ej1UYGDsSlSuI23VujR+0=,tag:apWpXVNt673LahtdnXeNqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
