apiVersion: ENC[AES256_GCM,data:MUI=,iv:N4SSbAuV/zXwdEwRx//mXO2c+iEVPHzsGm4fAltfb74=,tag:8jaIhwP2tPDJe1lAW9hDYg==,type:str]
kind: ENC[AES256_GCM,data:hgVdBJ4N,iv:wxUS1LFJ0t3azhoL09CbhfXujxM7ZzMir2zbFbduoS8=,tag:g8rFtL5epEvRYDXuBHr+Qg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FzF8ZQt/VF23bGcTioEoJQ==,iv:wrF0j8WPnfJbEn19smxOmjuNSXp/DtslS+FP+kuo+Ho=,tag:JBzaVS+bHUHRmvOwKEl+Ug==,type:str]
    namespace: ENC[AES256_GCM,data:vqxsiKxD3grT,iv:/XV8Bj9DpwJKZ7DRdCkzCHWyf024biYShleZ0PtVddU=,tag:G4uNDLyuYsHlxww4S9V7Iw==,type:str]
type: ENC[AES256_GCM,data:9OEz2hGJ,iv:o11jXW/EG6DNcYQIvsDU9rK1ZNvPAAXSKeXUYUxEKAc=,tag:dnT++L5jHPC8QwmYSRPrXQ==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:CnL5JFeECEMwtOqLxTOsktmm62lnxKrhR3mh36aHlq8F9Igqy9dxPOn/Cgt2Mw682gsKQ3tE47L7uGKAG4HRPl/SXaJZBDWevgY6Rpk0lLz/j3Y1mgw0A4msCkzdb1tTiFZUVJAU95rDnSa+A/bs85LkFoayC2lyAc8SleAxo4JlXSoyPzFY0XZ33fW+hFIPmzjZ63EI66C19ZFwpusjz29f+s9HyZ73/N6eX1WWHKf1eZioN0IzpkIrYmLJHRPvNj1xzwjogl8bRc4Bruo3PehaSduCgj70I6p0sgs5khr68FjZNGLA9p2GnFmA2f/KU2DvrDTMdcK2cniSFJmXd8oLDGdIGIPLM4pc1HaPjgcQIieGNnp0RDl6GGwbHy0pXVicMNSYJtoVDDDdVixyc4snyEvtt/bKqKCqD8Mp169vaLMoni/D6QH4xz2LtiL9u1J/NiBgjC7LPdvRizIcO0R8mGBAtc7fRLlY8HcWXEwE0uLHZ/BRHAMeJHsWO7qnRdLsQy4JvgkmwlKsvinY8PKxBVXrNMcQdovR8DvOTp5z9LrT27BTusso,iv:dJcvEebMpo9HrB9+Al57Aoo1CvE2gVWriMDly6GQC3Y=,tag:BOpIwMbWzHhoU5jH5/Tdng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN3NZaXdjdTRoeitBSUNO
            SXdwMW1remtpbmlEQ2VteXVKTzBBdVpVK2tnCkwwSmFYa0F1NEtJbmVyRVd4RFBU
            c3pyQmlRMG9pQmdnQ2pKQ0h2T0c0YTgKLS0tIFF4QXFyMjJxeWFvWGJiM00yM2hL
            amY3a1hvYUV0MDlrcjQ3VWg4ZGU3czgK6DF7nd+mCCze4YpRqm/le5a0kty/u8iR
            hMZfLiFo7XHLT9CQASA38eKvhPLsCpBwlK8ICLVJlhLQTkSDe3dFIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xgfvsdpafpfg8h459ulakcjq4lz7jwhy5qtfmphke0kukkd7xyusu83ajs
    lastmodified: "2026-05-17T12:26:40Z"
    mac: ENC[AES256_GCM,data:B24CSwWwyCBH0CmTnc37BEnsOAS3WhaHM9gYMOASY6GUUOKEAlBlQU4AzVS2HejF8+VnIv4rJyrZRRZJUA2IUnnPdq7sKQT2fEgeOn6zDiQHy3tBf8lLAIDFLCaRIjMaMXEtUhYOa4vOsdmyq8db7jpxkON0chA/eF9IkBV6Qpc=,iv:Cc5Q3ZEnIGngSjHXMnUQCt5lh5ueABGL3MD4FGK6uTc=,tag:6o7k0qwdWxLIeW0ZA9qOLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
