# Configuration SOPS pour NOAH
# Génération automatique - Fri Aug 15 10:01:54 2025

creation_rules:
- age: age1jmf2gt840ldzma7j6qx63xs0esgtlh73epcqyx0k5rd5t44mwfvsm78ena
  path_regex: ansible/vars/secrets\.yml$
- age: age1jmf2gt840ldzma7j6qx63xs0esgtlh73epcqyx0k5rd5t44mwfvsm78ena
  path_regex: helm/.*/secrets\.ya?ml$
- age: age1jmf2gt840ldzma7j6qx63xs0esgtlh73epcqyx0k5rd5t44mwfvsm78ena
  path_regex: manifests/.*-secrets?\.ya?ml$
- age: age1jmf2gt840ldzma7j6qx63xs0esgtlh73epcqyx0k5rd5t44mwfvsm78ena
  path_regex: \.env\.(encrypted|sops)$
