# Configuration SOPS pour NOAH
# Génération automatique - Fri Aug 15 03:47:59 2025

creation_rules:
- age: age1r78mzeprg7ay06h2nwl5d9vhqnnp68gny9l4sjhz7vyvxw4jn5ws983zpw
  path_regex: ansible/vars/secrets\.yml$
- age: age1r78mzeprg7ay06h2nwl5d9vhqnnp68gny9l4sjhz7vyvxw4jn5ws983zpw
  path_regex: helm/.*/secrets\.ya?ml$
- age: age1r78mzeprg7ay06h2nwl5d9vhqnnp68gny9l4sjhz7vyvxw4jn5ws983zpw
  path_regex: manifests/.*-secrets?\.ya?ml$
- age: age1r78mzeprg7ay06h2nwl5d9vhqnnp68gny9l4sjhz7vyvxw4jn5ws983zpw
  path_regex: \.env\.(encrypted|sops)$
