#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# NOAH - Network Operations & Automation Hub
# Copyright (C) 2026 Nicolas Engel <contact@nicolasengel.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
NOAH Configuration Utilities
Extracted configuration management functions for reuse across the project
"""

import json
from pathlib import Path

import click
import yaml

from .config_loader import ConfigLoader


def show_configuration(service=None, format='yaml', ctx=None):
    """
    Show current configuration for a service or global configuration.
    
    Args:
        service (str, optional): Show configuration for specific service
        format (str): Output format ('yaml', 'json', 'env')
        ctx: Click context (optional)
    """
    loader = ConfigLoader()
    
    if service:
        # Show service-specific configuration
        try:
            config_data = loader.get_service_config(service)
            click.echo(f"Configuration for service: {service}")
            click.echo("=" * 50)
            
            if format == 'yaml':
                click.echo(yaml.dump(config_data, default_flow_style=False, indent=2))
            elif format == 'json':
                click.echo(json.dumps(config_data, indent=2))
            elif format == 'env':
                for key, value in config_data.items():
                    if isinstance(value, str):
                        click.echo(f"NOAH_{service.upper()}_{key.upper()}={value}")
        except ValueError as e:
            click.echo(f"Error: {e}", err=True)
    else:
        # Show global configuration
        global_config = {
            'domain': loader.get_global_domain(),
            'cluster_name': loader.get_cluster_name(),
            'environment': loader.get_environment(),
            'services': list(loader.service_configs.keys())
        }
        
        click.echo("Global NOAH Configuration")
        click.echo("=" * 30)
        
        if format == 'yaml':
            click.echo(yaml.dump(global_config, default_flow_style=False, indent=2))
        elif format == 'json':
            click.echo(json.dumps(global_config, indent=2))


def show_domains(ctx=None):
    """
    List all service domains and FQDNs.
    
    Args:
        ctx: Click context (optional)
    """
    loader = ConfigLoader()
    
    click.echo("NOAH Service Domains")
    click.echo("=" * 40)
    click.echo(f"Global Domain: {loader.get_global_domain()}")
    click.echo()
    
    click.echo("Service FQDNs:")
    for service in loader.service_configs.keys():
        fqdn = loader.get_service_fqdn(service)
        namespace = loader.get_namespace(service)
        ingress_enabled = loader.service_configs[service].get('ingress_enabled', False)
        
        status = "🌐" if ingress_enabled else "🔒"
        click.echo(f"  {status} {service:12} → {fqdn:30} (ns: {namespace})")


def generate_helm_values(service, output=None, custom_values=None, ctx=None):
    """
    Generate Helm values for a service with dynamic domains.
    
    Args:
        service (str): Service name
        output (str, optional): Output file path
        custom_values (str, optional): Custom values YAML file to merge
        ctx: Click context (optional)
    
    Returns:
        dict: Generated Helm values (if no output file specified)
    """
    loader = ConfigLoader()
    
    try:
        # Load custom values if provided
        custom_vals = None
        if custom_values and Path(custom_values).exists():
            with open(custom_values, 'r') as f:
                custom_vals = yaml.safe_load(f)
        
        # Generate Helm values
        values = loader.generate_helm_values(service, custom_vals)
        
        if output:
            # Save to file
            output_path = Path(output)
            loader.export_helm_values_file(service, output_path, custom_vals)
            return values
        else:
            # Print to stdout
            click.echo(f"# Helm values for {service}")
            click.echo("# Generated by NOAH ConfigLoader")
            click.echo(f"# Service FQDN: {loader.get_service_fqdn(service)}")
            click.echo("---")
            click.echo(yaml.dump(values, default_flow_style=False, indent=2))
            return values
    
    except ValueError as e:
        click.echo(f"Error: {e}", err=True)
        return None


def get_service_fqdn(service, component=None):
    """
    Get fully qualified domain name for a service.
    
    Args:
        service (str): Service name
        component (str, optional): Service component
    
    Returns:
        str: Fully qualified domain name
    """
    loader = ConfigLoader()
    return loader.get_service_fqdn(service, component)


def override_service_configuration(service, domain=None, subdomain=None, namespace=None, ctx=None):
    """
    Set service-specific configuration overrides.
    
    Args:
        service (str): Service name
        domain (str, optional): Override service domain
        subdomain (str, optional): Override service subdomain
        namespace (str, optional): Override service namespace
        ctx: Click context (optional)
    
    Returns:
        dict: Updated service configuration
    """
    loader = ConfigLoader()
    
    if service not in loader.service_configs:
        click.echo(f"Error: Unknown service {service}", err=True)
        return None
    
    # Set overrides in environment
    if domain:
        key = f'NOAH_{service.upper()}_DOMAIN'
        loader.set(key, domain)
        click.echo(f"Set {key}={domain}")
    
    if subdomain:
        key = f'NOAH_{service.upper()}_SUBDOMAIN'
        loader.set(key, subdomain)
        click.echo(f"Set {key}={subdomain}")
    
    if namespace:
        key = f'KUBERNETES_NAMESPACE_{service.upper()}'
        loader.set(key, namespace)
        click.echo(f"Set {key}={namespace}")
    
    # Return updated configuration
    return loader.get_service_config(service)


# Click command decorators for CLI integration
