#!/usr/bin/env python3
"""
NOAH Configuration CLI - Dynamic Domain Management
Demonstrates enhanced ConfigLoader capabilities for Helm chart management
"""

import click
import yaml
from pathlib import Path

# Handle both relative and absolute imports for standalone execution
try:
    from .config_loader import ConfigLoader
except ImportError:
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from utils.config_loader import ConfigLoader

@click.group()
def config():
    """NOAH Configuration Management CLI"""
    pass

@config.command()
@click.option('--service', help='Show configuration for specific service')
@click.option('--format', type=click.Choice(['yaml', 'json', 'env']), default='yaml', help='Output format')
def show(service, format):
    """Show current configuration"""
    loader = ConfigLoader()
    
    if service:
        # Show service-specific configuration
        try:
            config_data = loader.get_service_config(service)
            click.echo(f"Configuration for service: {service}")
            click.echo("=" * 50)
            
            if format == 'yaml':
                click.echo(yaml.dump(config_data, default_flow_style=False, indent=2))
            elif format == 'json':
                import json
                click.echo(json.dumps(config_data, indent=2))
            elif format == 'env':
                for key, value in config_data.items():
                    if isinstance(value, str):
                        click.echo(f"NOAH_{service.upper()}_{key.upper()}={value}")
        except ValueError as e:
            click.echo(f"Error: {e}", err=True)
    else:
        # Show global configuration
        global_config = {
            'domain': loader.get_global_domain(),
            'cluster_name': loader.get_cluster_name(),
            'environment': loader.get_environment(),
            'services': list(loader.service_configs.keys())
        }
        
        click.echo("Global NOAH Configuration")
        click.echo("=" * 30)
        
        if format == 'yaml':
            click.echo(yaml.dump(global_config, default_flow_style=False, indent=2))
        elif format == 'json':
            import json
            click.echo(json.dumps(global_config, indent=2))

@config.command()
@click.argument('service')
@click.option('--output', '-o', help='Output file path')
@click.option('--custom-values', help='Custom values YAML file to merge')
def helm_values(service, output, custom_values):
    """Generate Helm values for a service"""
    loader = ConfigLoader()
    
    try:
        # Load custom values if provided
        custom_vals = None
        if custom_values and Path(custom_values).exists():
            with open(custom_values, 'r') as f:
                custom_vals = yaml.safe_load(f)
        
        # Generate Helm values
        values = loader.generate_helm_values(service, custom_vals)
        
        if output:
            # Save to file
            output_path = Path(output)
            loader.export_helm_values_file(service, output_path, custom_vals)
        else:
            # Print to stdout
            click.echo(f"# Helm values for {service}")
            click.echo(f"# Generated by NOAH ConfigLoader")
            click.echo(f"# Service FQDN: {loader.get_service_fqdn(service)}")
            click.echo("---")
            click.echo(yaml.dump(values, default_flow_style=False, indent=2))
    
    except ValueError as e:
        click.echo(f"Error: {e}", err=True)

@config.command()
@click.argument('service')
def validate(service):
    """Validate service configuration"""
    loader = ConfigLoader()
    
    issues = loader.validate_service_configuration(service)
    
    if issues:
        click.echo(f"❌ Configuration issues for {service}:", err=True)
        for issue in issues:
            click.echo(f"  - {issue}", err=True)
    else:
        click.echo(f"✅ Configuration for {service} is valid")
        
        # Show service details
        config_data = loader.get_service_config(service)
        click.echo(f"\nService Details:")
        click.echo(f"  FQDN: {config_data['fqdn']}")
        click.echo(f"  Namespace: {config_data['namespace']}")
        click.echo(f"  Ingress: {'Enabled' if config_data['ingress']['enabled'] else 'Disabled'}")
        click.echo(f"  TLS: {'Enabled' if config_data.get('tls_enabled') else 'Disabled'}")

@config.command()
@click.option('--service', help='Generate for specific service only')
@click.option('--output-dir', default='./generated-values', help='Output directory for values files')
def generate_all(service, output_dir):
    """Generate Helm values for all services"""
    loader = ConfigLoader()
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    services = [service] if service else loader.service_configs.keys()
    
    for svc in services:
        try:
            values_file = output_path / f"{svc}-values.yaml"
            loader.export_helm_values_file(svc, values_file)
            click.echo(f"✅ Generated values for {svc}")
        except Exception as e:
            click.echo(f"❌ Failed to generate values for {svc}: {e}", err=True)

@config.command()
@click.argument('service')
@click.option('--domain', help='Override service domain')
@click.option('--subdomain', help='Override service subdomain')
@click.option('--namespace', help='Override service namespace')
def override(service, domain, subdomain, namespace):
    """Set service-specific configuration overrides"""
    loader = ConfigLoader()
    
    if service not in loader.service_configs:
        click.echo(f"Error: Unknown service {service}", err=True)
        return
    
    # Set overrides in environment
    if domain:
        key = f'NOAH_{service.upper()}_DOMAIN'
        loader.set(key, domain)
        click.echo(f"Set {key}={domain}")
    
    if subdomain:
        key = f'NOAH_{service.upper()}_SUBDOMAIN'
        loader.set(key, subdomain)
        click.echo(f"Set {key}={subdomain}")
    
    if namespace:
        key = f'KUBERNETES_NAMESPACE_{service.upper()}'
        loader.set(key, namespace)
        click.echo(f"Set {key}={namespace}")
    
    # Show updated configuration
    click.echo(f"\nUpdated configuration for {service}:")
    config_data = loader.get_service_config(service)
    click.echo(f"  FQDN: {config_data['fqdn']}")
    click.echo(f"  Namespace: {config_data['namespace']}")

@config.command()
def domains():
    """List all service domains and FQDNs"""
    loader = ConfigLoader()
    
    click.echo("NOAH Service Domains")
    click.echo("=" * 40)
    click.echo(f"Global Domain: {loader.get_global_domain()}")
    click.echo()
    
    click.echo("Service FQDNs:")
    for service in loader.service_configs.keys():
        fqdn = loader.get_service_fqdn(service)
        namespace = loader.get_namespace(service)
        ingress_enabled = loader.service_configs[service].get('ingress_enabled', False)
        
        status = "🌐" if ingress_enabled else "🔒"
        click.echo(f"  {status} {service:12} → {fqdn:30} (ns: {namespace})")

@config.command()
@click.argument('service')
@click.argument('component', required=False)
def fqdn(service, component):
    """Get FQDN for a service or service component"""
    loader = ConfigLoader()
    
    try:
        fqdn = loader.get_service_fqdn(service, component)
        click.echo(fqdn)
    except ValueError as e:
        click.echo(f"Error: {e}", err=True)

if __name__ == '__main__':
    config()