#!/usr/bin/env python3
"""
NOAH Configuration Utilities
Extracted configuration management functions for reuse across the project
"""

import click
import json
import yaml
from pathlib import Path
from .config_loader import ConfigLoader


def show_configuration(service=None, format='yaml', ctx=None):
    """
    Show current configuration for a service or global configuration.
    
    Args:
        service (str, optional): Show configuration for specific service
        format (str): Output format ('yaml', 'json', 'env')
        ctx: Click context (optional)
    """
    loader = ConfigLoader()
    
    if service:
        # Show service-specific configuration
        try:
            config_data = loader.get_service_config(service)
            click.echo(f"Configuration for service: {service}")
            click.echo("=" * 50)
            
            if format == 'yaml':
                click.echo(yaml.dump(config_data, default_flow_style=False, indent=2))
            elif format == 'json':
                click.echo(json.dumps(config_data, indent=2))
            elif format == 'env':
                for key, value in config_data.items():
                    if isinstance(value, str):
                        click.echo(f"NOAH_{service.upper()}_{key.upper()}={value}")
        except ValueError as e:
            click.echo(f"Error: {e}", err=True)
    else:
        # Show global configuration
        global_config = {
            'domain': loader.get_global_domain(),
            'cluster_name': loader.get_cluster_name(),
            'environment': loader.get_environment(),
            'services': list(loader.service_configs.keys())
        }
        
        click.echo("Global NOAH Configuration")
        click.echo("=" * 30)
        
        if format == 'yaml':
            click.echo(yaml.dump(global_config, default_flow_style=False, indent=2))
        elif format == 'json':
            click.echo(json.dumps(global_config, indent=2))


def show_domains(ctx=None):
    """
    List all service domains and FQDNs.
    
    Args:
        ctx: Click context (optional)
    """
    loader = ConfigLoader()
    
    click.echo("NOAH Service Domains")
    click.echo("=" * 40)
    click.echo(f"Global Domain: {loader.get_global_domain()}")
    click.echo()
    
    click.echo("Service FQDNs:")
    for service in loader.service_configs.keys():
        fqdn = loader.get_service_fqdn(service)
        namespace = loader.get_namespace(service)
        ingress_enabled = loader.service_configs[service].get('ingress_enabled', False)
        
        status = "🌐" if ingress_enabled else "🔒"
        click.echo(f"  {status} {service:12} → {fqdn:30} (ns: {namespace})")


def generate_helm_values(service, output=None, custom_values=None, ctx=None):
    """
    Generate Helm values for a service with dynamic domains.
    
    Args:
        service (str): Service name
        output (str, optional): Output file path
        custom_values (str, optional): Custom values YAML file to merge
        ctx: Click context (optional)
    
    Returns:
        dict: Generated Helm values (if no output file specified)
    """
    loader = ConfigLoader()
    
    try:
        # Load custom values if provided
        custom_vals = None
        if custom_values and Path(custom_values).exists():
            with open(custom_values, 'r') as f:
                custom_vals = yaml.safe_load(f)
        
        # Generate Helm values
        values = loader.generate_helm_values(service, custom_vals)
        
        if output:
            # Save to file
            output_path = Path(output)
            loader.export_helm_values_file(service, output_path, custom_vals)
            return values
        else:
            # Print to stdout
            click.echo(f"# Helm values for {service}")
            click.echo(f"# Generated by NOAH ConfigLoader")
            click.echo(f"# Service FQDN: {loader.get_service_fqdn(service)}")
            click.echo("---")
            click.echo(yaml.dump(values, default_flow_style=False, indent=2))
            return values
    
    except ValueError as e:
        click.echo(f"Error: {e}", err=True)
        return None


def validate_service_configuration(service, ctx=None):
    """
    Validate service configuration and return issues.
    
    Args:
        service (str): Service name
        ctx: Click context (optional)
    
    Returns:
        list: List of configuration issues
    """
    loader = ConfigLoader()
    return loader.validate_service_configuration(service)


def get_service_fqdn(service, component=None):
    """
    Get fully qualified domain name for a service.
    
    Args:
        service (str): Service name
        component (str, optional): Service component
    
    Returns:
        str: Fully qualified domain name
    """
    loader = ConfigLoader()
    return loader.get_service_fqdn(service, component)


def get_all_service_fqdns():
    """
    Get FQDNs for all configured services.
    
    Returns:
        dict: Dictionary mapping service names to FQDNs
    """
    loader = ConfigLoader()
    fqdns = {}
    
    for service in loader.service_configs.keys():
        fqdns[service] = loader.get_service_fqdn(service)
    
    return fqdns


def override_service_configuration(service, domain=None, subdomain=None, namespace=None, ctx=None):
    """
    Set service-specific configuration overrides.
    
    Args:
        service (str): Service name
        domain (str, optional): Override service domain
        subdomain (str, optional): Override service subdomain
        namespace (str, optional): Override service namespace
        ctx: Click context (optional)
    
    Returns:
        dict: Updated service configuration
    """
    loader = ConfigLoader()
    
    if service not in loader.service_configs:
        click.echo(f"Error: Unknown service {service}", err=True)
        return None
    
    # Set overrides in environment
    if domain:
        key = f'NOAH_{service.upper()}_DOMAIN'
        loader.set(key, domain)
        click.echo(f"Set {key}={domain}")
    
    if subdomain:
        key = f'NOAH_{service.upper()}_SUBDOMAIN'
        loader.set(key, subdomain)
        click.echo(f"Set {key}={subdomain}")
    
    if namespace:
        key = f'KUBERNETES_NAMESPACE_{service.upper()}'
        loader.set(key, namespace)
        click.echo(f"Set {key}={namespace}")
    
    # Return updated configuration
    return loader.get_service_config(service)


def export_all_helm_values(output_dir='./generated-values', services=None):
    """
    Export Helm values for all or specified services.
    
    Args:
        output_dir (str): Output directory for values files
        services (list, optional): List of services to export (default: all)
    
    Returns:
        dict: Dictionary mapping service names to export results
    """
    loader = ConfigLoader()
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    target_services = services if services else loader.service_configs.keys()
    results = {}
    
    for service in target_services:
        try:
            values_file = output_path / f"{service}-values.yaml"
            loader.export_helm_values_file(service, values_file)
            results[service] = {
                'success': True,
                'file': str(values_file),
                'message': f"Generated values for {service}"
            }
            click.echo(f"✅ Generated values for {service}")
        except Exception as e:
            results[service] = {
                'success': False,
                'error': str(e),
                'message': f"Failed to generate values for {service}"
            }
            click.echo(f"❌ Failed to generate values for {service}: {e}", err=True)
    
    return results


def get_ingress_configuration(service):
    """
    Get ingress configuration for a service.
    
    Args:
        service (str): Service name
    
    Returns:
        dict: Ingress configuration
    """
    loader = ConfigLoader()
    return loader.get_service_ingress_config(service)


def list_available_services():
    """
    List all available services with their configuration status.
    
    Returns:
        dict: Dictionary with service information
    """
    loader = ConfigLoader()
    services_info = {}
    
    for service in loader.service_configs.keys():
        config = loader.get_service_config(service)
        services_info[service] = {
            'fqdn': config['fqdn'],
            'namespace': config['namespace'],
            'ingress_enabled': config['ingress']['enabled'],
            'tls_enabled': config.get('tls_enabled', False),
            'default_subdomain': config.get('default_subdomain', service)
        }
    
    return services_info


# Click command decorators for CLI integration
def config_show_command():
    """Click command decorator for show configuration"""
    @click.option('--service', help='Show configuration for specific service')
    @click.option('--format', type=click.Choice(['yaml', 'json', 'env']), default='yaml', help='Output format')
    @click.pass_context
    def show(ctx, service, format):
        """Show current configuration"""
        show_configuration(service, format, ctx)
    return show


def config_domains_command():
    """Click command decorator for domains listing"""
    @click.pass_context
    def domains(ctx):
        """List all service domains and FQDNs"""
        show_domains(ctx)
    return domains


def config_helm_values_command():
    """Click command decorator for Helm values generation"""
    @click.argument('service')
    @click.option('--output', '-o', help='Output file path')
    @click.option('--custom-values', help='Custom values YAML file to merge')
    @click.pass_context
    def helm_values(ctx, service, output, custom_values):
        """Generate Helm values for a service with dynamic domains"""
        generate_helm_values(service, output, custom_values, ctx)
    return helm_values


def config_override_command():
    """Click command decorator for configuration overrides"""
    @click.argument('service')
    @click.option('--domain', help='Override service domain')
    @click.option('--subdomain', help='Override service subdomain') 
    @click.option('--namespace', help='Override service namespace')
    @click.pass_context
    def override(ctx, service, domain, subdomain, namespace):
        """Set service-specific configuration overrides"""
        override_service_configuration(service, domain, subdomain, namespace, ctx)
        
        # Show updated configuration
        config_data = ConfigLoader().get_service_config(service)
        click.echo(f"\nUpdated configuration for {service}:")
        click.echo(f"  FQDN: {config_data['fqdn']}")
        click.echo(f"  Namespace: {config_data['namespace']}")
    return override