apiVersion: v1
kind: Secret
metadata:
  name: samba4-secrets
  namespace: identity
stringData:
  admin_password: KuLpz29X#gVxm*InnCyUckfh
  domain_admin_password: j0GgFuuPJG2N4YccE3unuy1P
  kerberos_password: 3zs8kJu8oWFDLP1#rIivZG!v
type: Opaque
