---
# Mattermost Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mattermost.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.secretKey }}
  secret-key: {{ .Values.auth.secretKey | b64enc | quote }}
  {{- else }}
  # Placeholder when no secret key is configured
  placeholder: {{ "placeholder" | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.ldap.bindPassword }}
  ldap-password: {{ .Values.ldap.bindPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.mattermost.emailSettings.smtpPassword }}
  smtp-password: {{ .Values.mattermost.emailSettings.smtpPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.oidc.secret }}
  oidc-secret: {{ .Values.oidc.secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.mattermost.fileSettings.amazonS3SecretAccessKey }}
  s3-secret-key: {{ .Values.mattermost.fileSettings.amazonS3SecretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.mattermost.fileSettings.amazons3.secretAccessKey }}
  s3-compatible-secret-key: {{ .Values.mattermost.fileSettings.amazons3.secretAccessKey | b64enc | quote }}
  {{- end }}
