---
{{- if .Values.serviceAccount.create }}
# Mattermost Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mattermost.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mattermost.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}

---
{{- if .Values.rbac.create }}
# Mattermost Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mattermost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mattermost.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

---
# Mattermost RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mattermost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mattermost.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mattermost.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mattermost.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
