# Traefik Configuration for NOAH Infrastructure
# Provides HTTPS-only ingress with Let's Encrypt certificates

# Service configuration
service:
  enabled: true
  type: LoadBalancer
  annotations:
    # Cilium LoadBalancer integration
    service.cilium.io/global: "true"
    service.cilium.io/shared: "true"
  spec:
    # External traffic policy for better performance
    externalTrafficPolicy: Local

# Ports configuration
ports:
  web:
    port: 80
    expose: true
    protocol: TCP
  websecure:
    port: 443
    expose: true
    protocol: TCP
    tls:
      enabled: true
  traefik:
    port: 9000
    expose: true  # Dashboard port - expose for health checks
    exposedPort: 9000

# Deployment configuration
deployment:
  enabled: true
  kind: Deployment
  replicas: 1

# Resources
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"

# RBAC
rbac:
  enabled: true

# Persistence for ACME certificates
persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data

# Dashboard configuration
api:
  dashboard: true
  insecure: true

# Health check endpoint
ping:
  enabled: true
  entryPoint: "traefik"

# IngressClass configuration
ingressClass:
  enabled: true
  isDefaultClass: true

# Pilot telemetry (disable for security)
pilot:
  enabled: false

# Global arguments
globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

# Additional arguments for HTTPS and Let's Encrypt
additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"
  - "--certificatesresolvers.letsencrypt-prod.acme.email=admin@noah-infra.com"
  - "--certificatesresolvers.letsencrypt-prod.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt-prod.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.letsencrypt-staging.acme.email=admin@noah-infra.com"
  - "--certificatesresolvers.letsencrypt-staging.acme.storage=/data/acme-staging.json"
  - "--certificatesresolvers.letsencrypt-staging.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.letsencrypt-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

# Security context
securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

# Pod security context
podSecurityContext:
  fsGroup: 65532

# Health checks
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
