{{- if .Values.datasources.prometheus.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "noah.fullname" . }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "noah.labels" . | nindent 4 }}
data:
  prometheus.yaml: |
    apiVersion: 1

    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: {{ .Values.datasources.prometheus.url }}
      isDefault: true
      editable: true
      jsonData:
        timeInterval: "30s"
        queryTimeout: "60s"
        httpMethod: "POST"
{{- end }}
