{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "noah.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "noah.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with (include "noah.storageClass" .) }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
