---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - apply-plan-configmap.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
  - dns-records.yaml
  - provision-job.yaml
  - provision-config-job.yaml
