# Global HTTPS redirect middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: traefik
  labels:
    app.kubernetes.io/part-of: noah-infrastructure
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
# Security headers middleware for HTTPS
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik
  labels:
    app.kubernetes.io/part-of: noah-infrastructure
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customRequestHeaders:
      X-Forwarded-Proto: "https"
