{{- if .Values.persistence.enabled }}
{{- range $key, $volume := .Values.persistence.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gitlab.fullname" $ }}-{{ $key }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "gitlab.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $key }}
  {{- with $.Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range $.Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ $volume.size | quote }}
  {{- if $.Values.persistence.storageClass }}
  {{- if (eq "-" $.Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ $.Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
