---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.auth.adminPassword | default "admin123!" | b64enc | quote }}

---
{{- if .Values.ldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-ldap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  ldap-password: {{ .Values.ldap.bindCredential | default "" | b64enc | quote }}
{{- end }}
