apiVersion: v2
name: redis
description: Redis is an open source in-memory data structure store
type: application
version: 18.4.0
appVersion: "7.2.3"
home: https://github.com/bitnami/charts/tree/main/bitnami/redis
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/redis
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
