# NOAH Cilium CNI Configuration - SSO Ready
# This file configures Cilium to support Samba4 and Authentik SSO integration
# Network policies and service mesh configuration for secure communication

# Enable/disable the dependency
cilium:
  enabled: true

# Global NOAH settings
global:
  domain: noah-infra.com
  sso:
    enabled: true
    provider: authentik
    ldap_provider: samba4

# Cilium configuration overrides optimized for SSO
operator:
  replicas: 1
  
ipam:
  mode: kubernetes
  
# Enable strict kube-proxy replacement for better performance
kubeProxyReplacement: strict

k8sServiceHost: kubernetes.default.svc.cluster.local
k8sServicePort: 443

# Enable service mesh features for SSO communication
serviceMesh:
  enabled: true

# Enable L7 policy enforcement for application-level security
l7Proxy: true

# Enable Cilium Ingress Controller for domain routing
ingressController:
  enabled: true
  loadbalancerMode: shared
  service:
    type: LoadBalancer
  # Enable Gateway API for modern ingress
gatewayAPI:
  enabled: true
  
# Enable advanced load balancing features  
loadBalancer:
  algorithm: round_robin
  mode: snat

# Enable BGP for advanced networking (if needed)
bgp:
  enabled: false

# Hubble configuration with SSO integration
hubble:
  enabled: true
  relay:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
  ui:
    enabled: true
    backend:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 512Mi
    frontend:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 512Mi
    ingress:
      enabled: true
      className: nginx
      annotations:
        # NOAH SSO Integration for Hubble UI
        nginx.ingress.kubernetes.io/auth-url: "https://auth.noah-infra.com/outpost.goauthentik.io/auth/nginx"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.noah-infra.com/outpost.goauthentik.io/start?rd=$escaped_request_uri"
        nginx.ingress.kubernetes.io/auth-response-headers: "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
        cert-manager.io/cluster-issuer: "noah-ca-issuer"
        # Additional security headers
        nginx.ingress.kubernetes.io/server-snippet: |
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;
          add_header X-XSS-Protection "1; mode=block";
      hosts:
        - hubble.noah-infra.com
      tls:
        - secretName: hubble-tls
          hosts:
            - hubble.noah-infra.com

# Prometheus monitoring integration
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    
# Resource configuration
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# Network Policy Configuration for SSO Services
networkPolicy:
  enabled: true

# DNS configuration for proper service discovery
dnsPolicy:
  enabled: true

# Enable identity-aware proxying
identityAwareProxy:
  enabled: true

nodeSelector: {}
tolerations: []
affinity: {}

# Additional configuration for SSO integration
extraConfig:
  # Enable CRDs for network policies
  crd:
    install: true
  
  # Configure service mesh for SSO
  serviceMesh:
    enableTracing: true
    
  # Configure identity for services
  identity:
    allocator: kvstore
    
  # Configure encryption for inter-service communication
  encryption:
    enabled: true
    type: ipsec
