# NOAH Cilium CNI Configuration - Core Settings
# Simplified configuration that merges working settings

# Core Cilium configuration
kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443

# Enable flow logging for service map
flowLogsEnabled: true
monitorAggregation: maximum

# IPAM configuration
ipam:
  mode: kubernetes

# Operator settings
operator:
  replicas: 1
  # Enable CRD management for network policies and services
  enableIPv4: true
  enableIPv6: false

# Enable service mesh features
serviceMesh:
  enabled: true
l7Proxy: true

# Network policy enforcement  
policyEnforcement: default

# Resource configuration
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Hubble configuration with SSO integration
hubble:
  enabled: true
  # Enable flow collection and metrics
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - icmp
      - http
    # Enable service monitoring metrics
    serviceMonitor:
      enabled: false
    # Export flow metrics
    dashboards:
      enabled: false
  # Configure flow export for service map functionality (v1.18+ format)
  export:
    static:
      enabled: true
      filePath: "/var/run/cilium/hubble/events.log"
      fileMaxSizeMb: 10
      fileMaxBackups: 5
      fileCompress: true
  # Enable service observability
  observe:
    # Enable service map data collection
    historySize: 4096
  relay:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
  ui:
    enabled: true
    backend:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 512Mi
    frontend:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 512Mi
    ingress:
      enabled: true
      className: nginx
      annotations:
        # NOAH SSO Integration for Hubble UI
        nginx.ingress.kubernetes.io/auth-url: "https://auth.noah-infra.com/outpost.goauthentik.io/auth/nginx"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.noah-infra.com/outpost.goauthentik.io/start?rd=$escaped_request_uri"
        nginx.ingress.kubernetes.io/auth-response-headers: "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
        cert-manager.io/cluster-issuer: "noah-ca-issuer"
        # Additional security headers
        nginx.ingress.kubernetes.io/server-snippet: |
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;
          add_header X-XSS-Protection "1; mode=block";
      hosts:
        - hubble.noah-infra.com
      tls:
        - secretName: hubble-tls
          hosts:
            - hubble.noah-infra.com

# Prometheus monitoring integration (disabled until operator available)
prometheus:
  enabled: true
  serviceMonitor:
    enabled: false
