# NOAH Cilium CNI Configuration
# This file overrides default Cilium values with NOAH-specific settings

# Enable/disable the dependency
cilium:
  enabled: true

# Global NOAH settings
global:
  domain: noah-infra.com
  sso:
    enabled: true
    provider: authentik

# Cilium configuration overrides
# These values are passed to the Cilium subchart
operator:
  replicas: 1
  
ipam:
  mode: kubernetes
  
kubeProxyReplacement: partial

k8sServiceHost: kubernetes.default.svc.cluster.local
k8sServicePort: 443

hubble:
  enabled: true
  relay:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
  ui:
    enabled: true
    backend:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 512Mi
    frontend:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 512Mi
    ingress:
      enabled: true
      className: nginx
      annotations:
        # NOAH SSO Integration
        nginx.ingress.kubernetes.io/auth-url: "https://auth.noah-infra.com/outpost.goauthentik.io/auth/nginx"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.noah-infra.com/outpost.goauthentik.io/start?rd=$escaped_request_uri"
        nginx.ingress.kubernetes.io/auth-response-headers: "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
        cert-manager.io/cluster-issuer: "noah-ca-issuer"
      hosts:
        - hubble.noah-infra.com
      tls:
        - secretName: hubble-tls
          hosts:
            - hubble.noah-infra.com

prometheus:
  enabled: true
  serviceMonitor:
    enabled: false
    
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
