#ENC[AES256_GCM,data:oeZY/JRbG36zI+Fb298gs1Xflf/J2h++v8FgCsPUwqahAN5mUfpPGpqCnd6rOGKz,iv:8X1RAnRwQiSCLajZcUstzDuHYbP0g9bblklKafaIg0Q=,tag:WfAPdQHyiYi7LXs2qRrPSQ==,type:comment]
#ENC[AES256_GCM,data:l0eC2xHqph9NrgUHsHGM4cCgs33GcJUQE2T3mPKny/Aj0ZCdQgTA3IbKTQhvIQfHNjqtpQ9Y/L6tPoAiMQ==,iv:YzBoP3xtyFPI4iDLbAOUqq/y45VSP+5nklakUbjgapw=,tag:Zz9JcaYOyqmqbP/PW4S5rg==,type:comment]
#ENC[AES256_GCM,data:rB7Ru6dynL4rP9LYm0h5ACz3Tl0=,iv:aCTKzVQO4vkT0bA4sW0VAAYi2FKQjk3vcd2PvbF8BUQ=,tag:bi6FzeyrB1oxFOYh44ngUw==,type:comment]
vault_postgres_password: ENC[AES256_GCM,data:PNqZLf5iQb8f3i2arjdCOmuCMkrXghyxCg==,iv:JaxOyajwiVdG7Wpt6e6lAzyoUi7jbt4DCuKtPcEmNvQ=,tag:jSyYLc0W+1P8u3SFz+/j3w==,type:str]
vault_postgres_replication_password: ENC[AES256_GCM,data:i5uHJoXTAloxxOaaFBpx1Rc/nu7Kf6b05pnHTw==,iv:FsCTTs/0REQVvHbZD4rEhxVPSkOGZdMjYpV0+nVICwA=,tag:aGiaSqbz/rLsM8NlWaVrhg==,type:str]
#ENC[AES256_GCM,data:miRlkHsA2rcNmpNZag==,iv:dYl2JLyFHEo3/pEgB9Q68MJF6iZ99wZKNnuGtV/xOnY=,tag:92rD2WDLferxOY/FoVkMfQ==,type:comment]
vault_keycloak_admin_password: ENC[AES256_GCM,data:NbrHjLyzegGfK/oep28xE9amAiwhQ3NB,iv:LQKr3GV9QXHDlja9ZKzw9Q1uHt9iCVtJkkZCnBuqk0s=,tag:3xH+AWEoe1qW0rm10YeJFQ==,type:str]
vault_keycloak_db_password: ENC[AES256_GCM,data:TZTRq4wJ4ojXbpK5PkjIGEN2RpgG,iv:5o9jzxHQIbBrCcS7QuhMe8F4xH09riZqdiwiG9LJynA=,tag:jCBB6EXb6V6lD8P7TIMKDQ==,type:str]
#ENC[AES256_GCM,data:xhvAwHD2ig==,iv:qN2EOQ37Y54Z742/wgDV+sU7xCxSp4D1rSzwuYH1Lvo=,tag:hCeKftasIjrJObPp1lpSIQ==,type:comment]
vault_gitlab_root_password: ENC[AES256_GCM,data:2+CQNxI6siOonKrGS9CGdnfoMsKi,iv:OBX1fLh8Pw4eNsFlC/TSvFhoKD0kExZvt//eBGe9V8M=,tag:hK14yWLvHE0kY7m8WG6HiA==,type:str]
vault_gitlab_db_password: ENC[AES256_GCM,data:j47+EZVyIyRT+zxHUJ4UG1TB1g==,iv:NJbsVW+jdwGJYcCfMbAkHNhe/SK0Q9qmuRViWr5AT+Y=,tag:hbCWYckX3FBj0fpYXuyFGA==,type:str]
vault_gitlab_redis_password: ENC[AES256_GCM,data:g5ffZ7FSep3RLT/kTEex0nCWNC2ynA==,iv:lTm3E+/CRvQEzhDqEa19Jdk5BulR4E3gxz/cqlKy1Ag=,tag:IkBgHJQDbvWKhEDS2XxdTw==,type:str]
#ENC[AES256_GCM,data:3DsoAg3bSDI=,iv:jDoI6Amhr9QTJrU6VEsXe5hHOKFtkJMPre7B1DG2pXI=,tag:jaNbobsgY0ajEcp3Fn6t6Q==,type:comment]
vault_grafana_admin_password: ENC[AES256_GCM,data:U1AckFE4NZASI24XEO6en7ihkC0A410=,iv:3maI0t2ZVndVj8N1gDZpMV7SWh1shuExUXE9irVzN1A=,tag:upelWhar/7gDpJEPDer8nw==,type:str]
#ENC[AES256_GCM,data:0KVmKEZo7B38FPI=,iv:vbtHNl++pWdc6+dnTBO4A0iX0bnb67NgNA1YsBwjKAo=,tag:SvqSpN38O8C8ERdG86g6uQ==,type:comment]
vault_mattermost_db_password: ENC[AES256_GCM,data:gOEkZpM6OTYovxY8Ao7/OYldgXv0f5I=,iv:sGl6L5MQHDWjUX/vEXxMfpvOiNsvfvf85OpWjdZ0nWI=,tag:d5DQ/ur6E3Re5Nj20MMR+w==,type:str]
#ENC[AES256_GCM,data:Itrg0c4KpG/YqQ==,iv:3FQuq/pioWq+xJ16eLxJCJIaru+Xo1k6X5TV9V1om48=,tag:Ps2Zk9e8dbtv8EDiaBI7pg==,type:comment]
vault_nextcloud_admin_password: ENC[AES256_GCM,data:cHSjMe5CdP0qcMSx5dQ4Qpb1uNib7+IFRw==,iv:VvrZp9sqQXakQ5ndn7tJzWIDA260LLgm1TtSg2j8Sq0=,tag:MwSEAEK07noxJlb2rIImWg==,type:str]
vault_nextcloud_db_password: ENC[AES256_GCM,data:BFhw64cogBG1+3yXSyrQGwFO+kecSw==,iv:sd+diUspYxIwxm3AIjWWn5/PM4N1ZsLV9EpwQWDYoCM=,tag:eJiv76DA7C9EAQVfjMghnw==,type:str]
#ENC[AES256_GCM,data:wBUqkpKEMQEdl3iHCA==,iv:lwQkHzLsaB8KkqoLGUjdAEjHsRiaFwjBfrg+6vvU9W8=,tag:AuHzCQDpaEAQnSSNyXYjpw==,type:comment]
vault_oauth2_client_secret: ENC[AES256_GCM,data:lRWPSbuja9aKaye5+r8qq6qZsHjtHuyJyJBaMrk1,iv:S6YeK9pN/vwaA2H2TkHp0qv0kKj6Ed5SBB8hxWGZSq0=,tag:UWj+lo4uFWLGfmIYo8dZ6Q==,type:str]
vault_oauth2_cookie_secret: ENC[AES256_GCM,data:WuXAGhpAdzIvZ3AEjpiNic3DOV+u92TLLA7m0yxS,iv:RRUKSymAbJEo1VjQmlEvNDmhQzfHeBFtImIhs11GoBs=,tag:rx4oKU8WcUCzNgb6EnwZ0Q==,type:str]
#ENC[AES256_GCM,data:4apmsaba+OXhqxP2cuv/edMWKGBY,iv:ysRLxYoIZxGRp6cK0iKM/+PQa31wWgtLQl6oTYfHhyg=,tag:wbVEk7po809C4xwewo5uvg==,type:comment]
vault_ssl_private_key: ENC[AES256_GCM,data:MQ/5QDKCdsQNQSIrhZOaLigUkiRtDkUay0ymaGn+ksjik7tn/K/Jz0XNEk5f/O+/lm3SZ6BPk32pfyFHvJ158E/kC07C76EZe0m9wc2KNRBNZhVIaI/dM6Yq5wPzM6thklZoUUNCAey/PJ0GP6lGaQ==,iv:zD6Kwps/YY05gbPG1jOJYLLmjexMNtkamSJY/eyTPbM=,tag:5arQxFPMOinMuI6XMJXu5Q==,type:str]
vault_ssl_certificate: ENC[AES256_GCM,data:I4K2mZqgvN3be+cA5ZgFTAkytRVBKmBnomERLm1kSRwbyMKBrWj5S0PWhCR5HBaLQNR1vwtUKTdLvAWR1i3OZY8Qh79G3KWKh3v3vY/ij3c1t9b0fRFjKjLT/Z6iOUyYAvR3QG/rzpWmSOZRGqKyFQ==,iv:CN54c04mw83QP1lKTrCgh351HizEC8WB/tgX3u5zmpw=,tag:f8C03JF9aBcqmbbmN9FiIA==,type:str]
#ENC[AES256_GCM,data:TTPz3al8k9MnxoPfqF/tWA==,iv:ifiudn2lb7sRzhv1N8s800J343nzU9s96JQZ35fuQJk=,tag:yFMi241IypAIthP6KsyEGQ==,type:comment]
vault_jwt_secret: ENC[AES256_GCM,data:DS1QD7l0Q7ZUfzCA8Rg3eFcoyEAxm3G+,iv:NFGGYtGOrZmDAFBu+uj6G50hcAB/OjrEAC5mVp8Dmb0=,tag:J2wklAjRUICXi4b76NEm/A==,type:str]
vault_encryption_key: ENC[AES256_GCM,data:3z7iEPCHTxxL3YGNOonq3k8fqkZ5kb/U+KIOfv8Z2GWe,iv:6C8tX5upnr1wfCO+Em9CKJXjgprbbYKyqJzsyHef1Pk=,tag:GTFoTIXKpWLAPe56Fs8Umw==,type:str]
#ENC[AES256_GCM,data:SM8Z5BKPyIAmOCoCnWfsJ09Ukg==,iv:vhN5YkN9o1VddB3zLykELZI+z9OcYBFSIQu0q2N1Kyw=,tag:1K/jlh0KALWsxu7xLK453A==,type:comment]
vault_smtp_password: ENC[AES256_GCM,data:nuB4ib05qu3QwIYq1Qn9DngUVhNIfAs=,iv:hCd4bxqUleifesWuYkaG8kFYVarBwYvGzCMdVkxUGq8=,tag:vn0JptBh4tWp/VZPcvfNoA==,type:str]
#ENC[AES256_GCM,data:yETetC1aeaXPlk+72tvMsdaF,iv:+1+oAgEeGSSyjIok6rN/d0JHAqPcKOCc6NvWWPe+sk4=,tag:lRpvK0Cm9VEvP2ESS3w98g==,type:comment]
vault_backup_encryption_key: ENC[AES256_GCM,data:tRYDCE023VMyvnIBTBGU+NPInMI=,iv:XU481KsuG3+pEayZPzgea/tqF6jcpPinu/QJxWb/u98=,tag:cEqzIZwjtr3HkKkVwhkNbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eupew2tgf2024zn4j6uwer6e8rakyag4g5mzws2myqkddz8yvfqvzrnha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y3RFOTFWWHJydWlIQlBk
            djh2UU8wWDd2VGNRVEF5aVMvRytPKzI2VGhNCkNrT3YzRURQSWEzaVJJZDl3MDdL
            QTdySkc0ZGJXMGlKWUkyZ0t2bTY1YncKLS0tIENkcEFTekxSalhYamVWSDFZNmdW
            N1pmRTdLMHZHU1JoN05XeTh1ZDZBakkKtC9EGGLgkhSsjG544aDIgQwycp8Eo5cb
            IlYTZ+gYTX8BtDTMzYyMCEBBCvlRFOhxP0VDrVx1elcPZMZCEjk4PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T09:15:33Z"
    mac: ENC[AES256_GCM,data:0Fx80B3ijx9zPY/2kdDzV0QM5dgU/JCZYvB53/134gl+vl0s+SkLEeJUcbYb28PnpiYIp+JNLi3xj/PckJS47a2Sm6SbNcheGsP8hj4Ztt/xVx2VfsuCaGCsQViOKUpY2iSTNntfpKSes3OLHA6tB0JPfZVpLcDn9YoUikoYBsw=,iv:WNEN+xjmPkVV+GToyRWFK8lj+QkKkb2IAmnQ8QqoZ2E=,tag:0xnd56iigk9oDOhebA5bjw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
