apiVersion: v1
kind: ConfigMap
metadata:
  name: samba4-config
  labels:
    {{- include "samba4.labels" . | nindent 4 }}
data:
  smb.conf: |
    [global]
        workgroup = {{ .Values.domain.name }}
        server string = Samba Server %v
        netbios name = {{ .Values.domain.netbiosName }}
        security = user
        map to guest = bad user
        dns proxy = no
        
        # Logging
        log level = 1
        log file = /var/log/samba/log.%m
        max log size = 1000
        
        # Performance and compatibility
        socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=524288 SO_SNDBUF=524288
        read raw = yes
        write raw = yes
        
        # SMB protocol versions
        min protocol = SMB2
        max protocol = SMB3
        
    [data]
        comment = Samba Data Share
        path = /data
        browseable = yes
        read only = no
        guest ok = no
        valid users = admin
        create mask = 0775
        directory mask = 0775
