apiVersion: v1
kind: ConfigMap
metadata:
  name: samba4-config
  labels:
    {{- include "samba4.labels" . | nindent 4 }}
data:
  smb.conf: |
    # Global parameters
    [global]
        netbios name = {{ .Values.domain.netbiosName }}
        realm = {{ .Values.domain.realm }}
        server role = active directory domain controller
        workgroup = {{ .Values.domain.name }}
        dns forwarder = {{ .Values.domain.dnsForwarder }}
        
        # Security settings
        server signing = mandatory
        ldap server require strong auth = yes
        
        # Logging
        log level = 1
        log file = /var/log/samba/log.%m
        max log size = 1000
        
        # TLS configuration
        tls enabled = yes
        tls keyfile = /etc/samba/tls/tls.key
        tls certfile = /etc/samba/tls/tls.crt
        tls cafile = /etc/samba/tls/ca.crt
        
    # SYSVOL and NETLOGON shares
    [sysvol]
        path = /var/lib/samba/sysvol
        read only = No
        
    [netlogon]
        path = /var/lib/samba/sysvol/{{ .Values.domain.realm | lower }}/scripts
        read only = No
