apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "samba4.fullname" . }}
  labels:
    {{- include "samba4.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "samba4.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "samba4.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: init-samba
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Initializing Samba4 data directory..."
          mkdir -p /data
          mkdir -p /var/lib/samba/private
          mkdir -p /var/lib/samba/lock
          mkdir -p /var/cache/samba
          mkdir -p /var/log/samba
          chmod 755 /data
          chmod 755 /var/lib/samba/private
          echo "Initialization complete"
        volumeMounts:
        - name: samba-data
          mountPath: /data
        - name: samba-data
          mountPath: /var/lib/samba
          subPath: lib
        securityContext:
          runAsUser: 0
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DOMAIN
          value: {{ .Values.domain.name | quote }}
        - name: DOMAINPASS
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.auth.externalSecrets }}samba4-security-secrets{{ else }}{{ include "samba4.fullname" . }}-secrets{{ end }}
              key: {{ if .Values.auth.externalSecrets }}SAMBA_ADMIN_PASSWORD{{ else }}SAMBA_ADMIN_PASSWORD{{ end }}
        - name: DNSFORWARDER
          value: {{ .Values.domain.dnsForwarder | quote }}
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: smb
          containerPort: 445
          protocol: TCP
        - name: netbios
          containerPort: 139
          protocol: TCP
        - name: ldap
          containerPort: 389
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 389  # Check LDAP port for AD DC
          initialDelaySeconds: 180  # AD DC takes longer to start
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 389  # Check LDAP port for AD DC
          initialDelaySeconds: 120  # AD DC takes longer to start
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: samba-data
          mountPath: /data
        - name: samba-data
          mountPath: /var/lib/samba
          subPath: lib
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      volumes:
      - name: samba-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
        emptyDir: {}
        {{- end }}
