apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "samba4.fullname" . }}
  labels:
    {{- include "samba4.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "samba4.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "samba4.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: init-samba
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Initializing Samba4 data directory..."
          mkdir -p /var/lib/samba/sysvol
          mkdir -p /var/lib/samba/private
          mkdir -p /etc/samba/tls
          chown -R 1000:1000 /var/lib/samba
          echo "Initialization complete"
        volumeMounts:
        - name: samba-data
          mountPath: /var/lib/samba
        securityContext:
          runAsUser: 0
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SAMBA_DOMAIN
          value: {{ .Values.domain.name }}
        - name: SAMBA_REALM
          value: {{ .Values.domain.realm }}
        - name: SAMBA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: samba4-secrets
              key: SAMBA_ADMIN_PASSWORD
        - name: SAMBA_DNS_FORWARDER
          value: {{ .Values.domain.dnsForwarder }}
        - name: SAMBA_NETBIOS_NAME
          value: {{ .Values.domain.netbiosName }}
        ports:
        - name: ldap
          containerPort: 389
          protocol: TCP
        - name: ldaps
          containerPort: 636
          protocol: TCP
        - name: kerberos
          containerPort: 88
          protocol: TCP
        - name: kerberos-udp
          containerPort: 88
          protocol: UDP
        - name: kpasswd
          containerPort: 464
          protocol: TCP
        - name: smb
          containerPort: 445
          protocol: TCP
        - name: netbios
          containerPort: 139
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 389
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 389
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: samba-data
          mountPath: /var/lib/samba
        - name: samba-config
          mountPath: /etc/samba
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      volumes:
      - name: samba-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: samba-config
        configMap:
          name: samba4-config
