{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "samba4.fullname" . }}-network-policy
  labels:
    {{- include "samba4.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "samba4.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow LDAP access from Authentik
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.allowFromNamespace | default "identity" }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: authentik
    ports:
    - protocol: TCP
      port: 389
    - protocol: TCP
      port: 636
  # Allow SMB/NetBIOS access
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.allowFromNamespace | default "identity" }}
    ports:
    - protocol: TCP
      port: 445
    - protocol: TCP
      port: 139
  # Allow Kerberos access
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.allowFromNamespace | default "identity" }}
    ports:
    - protocol: TCP
      port: 88
    - protocol: UDP
      port: 88
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow all egress to same namespace
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.allowFromNamespace | default "identity" }}
{{- end }}
