{{- if not .Values.auth.externalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "samba4.fullname" . }}-secrets
  labels:
    {{- include "samba4.labels" . | nindent 4 }}
  annotations:
    # Indicate this should be managed by external secret management
    noah.infra.com/secret-type: "samba-credentials"
    noah.infra.com/rotation-policy: "30d"
    noah.infra.com/fallback-secret: "true"
type: Opaque
data:
  # Format: base64 encoded "username;password"
  samba-user-config: {{ printf "admin;%s" (.Values.auth.adminPassword | default (randAlphaNum 32)) | b64enc | quote }}
  # Individual components for other uses
  admin-username: {{ "admin" | b64enc | quote }}
  admin-password: {{ (.Values.auth.adminPassword | default (randAlphaNum 32)) | b64enc | quote }}
  # Domain configuration
  domain-name: {{ .Values.domain.name | b64enc | quote }}
  workgroup: {{ .Values.domain.name | b64enc | quote }}
{{- end }}
