---
apiVersion: v1
kind: Service
metadata:
  name: samba4
spec:
  selector:
    app: samba4
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 389
      protocol: TCP
      name: ldap
  type: {{ .Values.service.type }}
