#ENC[AES256_GCM,data:Y/NhQMQ85x39K/Rh/3v+eBmHxK5VQQO2MygHhkojS6vT+5i2mwFxlH6mTwXjkMue++Sj2gjKbZ3dEsjTNWFk96ZLrx/fvEwz,iv:8xp3WTLNi6dzgRJUtiOh+YDJv9h8gl80fS9U9jqEvrg=,tag:+e1NcFCJFeGoFuvcVSRUig==,type:comment]
#ENC[AES256_GCM,data:hJJaSs4eFLBTzcgs4530zBFy4Iy3jXlQhks3MYea0S4FBbpmSO7TNpKOuXySJznsWeTjV55VhH6yyL7aSMkNjOwN/g==,iv:3Y8sfhEeT8705VzBvd6FZjWoQxaQ7nyQGUkNTUwfbM4=,tag:Lv4zkgvccbmgKGMv4irQwQ==,type:comment]
#ENC[AES256_GCM,data:DqnGi2vOX7GkfUMloy63uycxrttSDn8mCK9pyW9U+S4fdQpHnQlphCP2fDmodukgNnWt9TkE7yIX0F3Odp05iPvE,iv:RaOdjXRIbZ0rN8/UV784ESpkJjOF+/N9CGr3sEra2Rc=,tag:cZ3jTfQxnCCtsIoe+bntjw==,type:comment]
#ENC[AES256_GCM,data:45KdrtF3uL35VTb1DxvGdxoGFkIKRY7qPAGCSZ9RodVv2eAQ/+t5A9KV8RA90tOETtiZKLNlIBRlzPMtaRYr,iv:LAVRpd6O0NZQvT7Jb2IOR4tVyMcH1K0tN1/Bwe1U9ZI=,tag:yzaRKKu8OqsMyjY0sKgTeA==,type:comment]
apiVersion: ENC[AES256_GCM,data:1A0=,iv:bsIaaeLTiZtc03X2FtKtTzkArPhg4oClqmfyx9k3Ty4=,tag:dMr+28yVlGnnMQ6snWAp9g==,type:str]
kind: ENC[AES256_GCM,data:MnClCyQo,iv:HGXTtyWzXbZD00ImTx+Sy78DRPqPCmBHvxtv+/Jk6f4=,tag:3BhI8kbdY3RwfwpA12YoAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JuqTjQTXbVHKSFaKsHe0EpJcwJY=,iv:gTC+lnBxzrR6bAmGrohj04fM2FHqqi42LyDK0E1VBnc=,tag:V9so6ZbctZUsMiYocTyd4w==,type:str]
    namespace: ENC[AES256_GCM,data:/ySF2EdVhGV+9Pkb,iv:FbXYirwg8QfNw8FrCHgm2naTB59Ed444RgoBrrW/NpA=,tag:ljctpnsrLs4VPHZJnh/yew==,type:str]
type: ENC[AES256_GCM,data:Ofa9Nyal,iv:1pEAS9alivqW5rEdE7J4poWvZWDUGwq0iN4zcNAexjU=,tag:kL5wOCCsYr/St64fCM9E6w==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:EhlNmEqYonBbS2llgXbd6oAi9zCtNw3tqr+gb2ADfIWZ+6B6mM9scOhzpTbFWToOgJPYCPE=,iv:Vv9aTngN3VB048B62aoB5Q7YZmmZXmaBJZWqFrrl2sQ=,tag:6+svB9guUuqdpWhjUFCsjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK2V1dmd1aytReVNFekMx
            L3ovYWJ6YW9TVldVeHVZcktCdk1iZ3lVbFhvCjRDVDIrRFdTSCtKK1J0YitJcTQv
            em9HZnlWaGRTbG1tcmQrNHNCYldxakkKLS0tIFVHMkM0YkkwcWNveUUza1JRUG8w
            ekQ0STdCLzg3US9kbUFXbWZBUStYSFEKc466iS4gs5gCdzmYb/j2sOenKvqrIyG/
            FU2r1sxoSflRAbEbDnszXXoZXKRO3qTKTeLPZeQ1R8wCe3jNR1P4Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lf53pymuyys7tl4t89v27q0dmfkdqg0mxme7z7cqh2vefx8naanqwvlhtx
    lastmodified: "2026-05-15T08:56:10Z"
    mac: ENC[AES256_GCM,data:MS+0EU+cWcXTVSSuXuOukY1I55lkxz5/bkrTtrLzRtYazi/rb+bkHlC4hmbN1riC4BPA7MWj0yFspnPtGPdzMoA+87tMypzMN7NXoDC0KuURUsHly68ITMcGPoNqmg3Z0sbh1aPHFCF2fcHnYDvmP+uYq8TxiCNyG0YA96JuMkg=,iv:DOHlMMZuZgzRWY7gAhCOAE/oXzwcVqS0o4LjT8FeZys=,tag:9Xz0rPbuCQXJrpeIssciqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
