{{- if .Values.ingress.enabled }}
---
# Cilium-powered Ingress for Authentik SSO
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "authentik.fullname" . }}-cilium
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
  annotations:
    # Use Cilium as ingress controller
    kubernetes.io/ingress.class: cilium
    # Enable HTTPS redirect
    cilium.io/ssl-redirect: "true"
    # Configure load balancing
    cilium.io/lb-algorithm: round_robin
    # Enable service mesh features
    cilium.io/service-mesh: "true"
    # Configure timeout for SSO flows
    cilium.io/proxy-read-timeout: "300s"
    cilium.io/proxy-send-timeout: "300s"
    # Enable CORS for SSO integration
    cilium.io/cors-enable: "true"
    cilium.io/cors-allow-origin: "*"
    # Security headers
    cilium.io/response-headers: |
      X-Frame-Options: DENY
      X-Content-Type-Options: nosniff
      X-XSS-Protection: 1; mode=block
      Strict-Transport-Security: max-age=31536000; includeSubDomains
spec:
  rules:
  - host: {{ .Values.ingress.hosts.host | default "authentik.noah-infra.com" }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "authentik.fullname" . }}-server
            port:
              number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts.host | default "authentik.noah-infra.com" }}
    secretName: {{ .Values.ingress.tls.secretName | default "authentik-cilium-tls" }}
  {{- end }}
{{- end }}
