apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authentik.fullname" . }}-config
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
data:
  oidc-config.yaml: |
    {{- if .Values.authentik.oidc.enabled }}
    oidc_providers:
      - name: "Kubernetes Cluster OIDC"
        client_id: {{ .Values.authentik.oidc.clientId | quote }}
        issuer_url: {{ .Values.authentik.oidc.issuerUrl | quote }}
        authorization_flow: "default-authentication-flow"
        redirect_uris:
          - "http://localhost:8080"
          - "https://kubernetes.noah-infra.com/oauth/callback"
        scopes:
          - "openid"
          - "profile"
          - "email"
          - "groups"
        property_mappings:
          - "authentik default OIDC Mapping: OpenID 'sub'"
          - "authentik default OIDC Mapping: OpenID 'email'"
          - "authentik default OIDC Mapping: OpenID 'email_verified'"
          - "authentik default OIDC Mapping: OIDC Groups Claim"
    {{- end }}
  
  bootstrap-config.yaml: |
    bootstrap:
      admin_user: {{ .Values.authentik.bootstrap.adminUser | quote }}
      admin_email: {{ .Values.authentik.bootstrap.adminEmail | quote }}
      
  app-config.yaml: |
    # Authentik application configuration
    server:
      listen:
        - "0.0.0.0:9000"
      cookie_domain: ".noah-infra.com"
      cookie_secure: true
    
    logging:
      level: {{ .Values.authentik.logLevel | quote }}
      
    email:
      {{- if .Values.authentik.email }}
      host: {{ .Values.authentik.email.host | quote }}
      port: {{ .Values.authentik.email.port }}
      username: {{ .Values.authentik.email.username | quote }}
      use_tls: {{ .Values.authentik.email.useTls }}
      use_ssl: {{ .Values.authentik.email.useSSL }}
      from: {{ .Values.authentik.email.from | quote }}
      {{- end }}
