apiVersion: v1
kind: Service
metadata:
  name: cilium-ingress-lb
  namespace: kube-system
  labels:
    app: cilium-ingress-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 65.21.238.126
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 9443
    protocol: TCP
  selector:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: server
  externalTrafficPolicy: Local
