apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.fullname" . }}-server
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.httpsPort }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "authentik.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
---
{{- if .Values.authentik.outposts.ldap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.fullname" . }}-ldap
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: ldap-outpost
spec:
  type: ClusterIP
  ports:
    - port: 389
      targetPort: ldap
      protocol: TCP
      name: ldap
    - port: 636
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    {{- include "authentik.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ldap-outpost
{{- end }}
