noah:
    version: ENC[AES256_GCM,data:GaEC0Ew=,iv:RNMwR+nr+TmogZkUVyKIuGS28LAU2/hpYJzbPYdn+68=,tag:M9M+d3JqkxwJQeBgZYOv6w==,type:str]
    domain: ENC[AES256_GCM,data:o0ghM5YwlX+IQEVal4M=,iv:1AKb4XpPEFtEPooNeElcSejKB1iT155Kq3y41LKx2kY=,tag:ksrVZI2l0FFZA4wRi7c7Yw==,type:str]
kubernetes:
    cluster_name: ENC[AES256_GCM,data:FcKc1OVNdXNJfL0O,iv:dAJyWybf5JCH+p16wgKaxX/AJPm6RTtmO+TbAFMofpc=,tag:2Nsq6rjgQ30gscI7aWrFgQ==,type:str]
    namespace_identity: ENC[AES256_GCM,data:swX3xEkHeUA=,iv:O/1uOOGpuzRb+oTuz6SCY9CUe25siy0+JoGeKmfvatA=,tag:QKLPsqIaELo9E63/sHNVcQ==,type:str]
    namespace_network: ENC[AES256_GCM,data:tIe7NimEXg==,iv:1JJ0EMt/Kg+TZsn32cSfO4reX99ecZhzUWTnINX5Ewg=,tag:zimsknRyWzyyM8vNHQ+xoA==,type:str]
    api_version: ENC[AES256_GCM,data:f/0=,iv:gDmwHLryQzmvqNQXK7OgEI6XhaUigwvcP5XN0YXLpsM=,tag:jEPBzo9SC6r4/gYjcWi3jg==,type:str]
authentik:
    secret_key: ENC[AES256_GCM,data:2X1wE7UMslI9Q08K6LBRz66IJFPnUJYjbg9f2xkXaaKhhCVD,iv:w7ZoiFPFwzh147sAan3bWx51JMUIk/JKsHcfZy0DX5g=,tag:SR+qyep/oHMJk3DI/Ea+cg==,type:str]
samba4:
    admin_password: ENC[AES256_GCM,data:ZPTWxgQL5uw+4HUA/wLRc4YNa7rMi7PuOIrLYYIg5t4TVtab,iv:Fs29d8GGIPEkhX8v/dbOJiGyUZvdW5JG189zQLAlCho=,tag:sAmMz8WxWLl0As0Irq/BPA==,type:str]
    domain: ENC[AES256_GCM,data:YJ6f9w==,iv:vyQObE19PhOc3siVNYHqyqOyMRIqnCHFXsIyOre2IL0=,tag:TkJ6xl+NuJPXVqwHq2tmaQ==,type:str]
    realm: ENC[AES256_GCM,data:KuH6SnYsDQ2NeA==,iv:lN6DGgniQ0jC6pFbyW/2Wm5qMTgZSDL9nXo5xAK0JhE=,tag:WmsqMBtQYprea4EVICET5Q==,type:str]
certificates:
    ca_key_password: ENC[AES256_GCM,data:37E+SaGYeqcjliKIjTOhoz2eY0NSvkicxaay,iv:Yenm9F5+OUuDDCR0fw9QcCqVBSBbo9uiKSzM96ws3eY=,tag:jrGnPJJor6m6tcjjcnOqYA==,type:str]
secrets:
    encryption_key: ENC[AES256_GCM,data:qpXG+dfNu0L2fjkDUSLtfR+U906CXaTJ+H6VpfDh,iv:d/Yu1rA6HuAqg5AqcEWLSciZKC9lfuQRkXB+z4ulLlc=,tag:SlAjwPtcHZpovMvzoZYp6w==,type:str]
paths:
    secrets_dir: ENC[AES256_GCM,data:lGYVGi1geg==,iv:QpQxGaGfo8wfcXxTwBfIck9ybFd0A5AtOJM3Ao2OFcs=,tag:ABtMYkcYORUBvU1qdqSAXw==,type:str]
    certificates_dir: ENC[AES256_GCM,data:HtAQBg+hyPGEKojU,iv:t8cCfR4ZJWDDfXSR643O4tTgvHWiYT6/srNFBJ4wsy0=,tag:Uj6fK+jMzjiPwVhh3qbszw==,type:str]
    config_dir: ENC[AES256_GCM,data:kyl/0Qqw,iv:ET+5wN7qRT09+thDxdFeVaF6LdsXEYPcM9Q9rxo0tqg=,tag:XRjaV0AG80ts2+BuHfz0Xw==,type:str]
    ansible_dir: ENC[AES256_GCM,data:IoS0jp7rLA==,iv:AhpBiN5p4U2gQ7e2B6jLcDKLDglwB69GQi4lblAmzWc=,tag:jzNKloSiq5WLHXIP1vAdtg==,type:str]
    playbook_dir: ENC[AES256_GCM,data:xBUVzriVJQ==,iv:0Z2rqCMKQ7Dl3gC7OzURZ9kqn9gSFKqSSPX0N9O5+3I=,tag:d+L7Y1Lm0dfpVrX8fw7eQQ==,type:str]
helm:
    chart_dir: ENC[AES256_GCM,data:SQLoOQ==,iv:l48UFoPMmZqNG4lY3uV5Dr28oMv4otAv2NhdNNnBqtU=,tag:arpvZPg/SaBDi6HdqmGWfQ==,type:str]
    values_dir: ENC[AES256_GCM,data:U3HgKsKYBS8q4rk=,iv:hs2XBkTiod6H5uW/iCeO6XGen5P2E0zW90frfDSvlKs=,tag:3uTGAj7xaXro7g2BAKUJ3w==,type:str]
    timeout: ENC[AES256_GCM,data:fVfYaA==,iv:ZUBXfpF6xqjSPCgUp1i6PjPAc7Bc9m2R+ruoBvabim4=,tag:R9ah8cV8PyNbVWbPXA0DRA==,type:str]
sops:
    age:
        - recipient: age1wg8lawlpysvhj9k7tp7x385pv4saznpnglx2v20ll2qpnc4kny6squ3q64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QWVBK0lQR0tLc01EM1l3
            NkpOMmhKais1ZjZFSlVmZmFWa2p2ejRLSEVRCmlORGdNN3lTWmhEUmdnakZEbzhZ
            UzEyYmt2MytlTTFYVXFsSSt4dUc3WlUKLS0tIEZZcDA0ZXp1L3BGeTBtR1BHMTMx
            ajgvRFllR1czRkJsL1I0bElaWjRVNmcKE/5ujEoitsLRpEOfOTunZzZe+zg//wM4
            thbiz3FY5oKq0nKrIuJyH6HRCuwQOGmvYstP3bh6F9IZNDJI3j3csA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T18:25:01Z"
    mac: ENC[AES256_GCM,data:kMUo7mlCHn+AxokbsrW0NqI/w7lJeljR0yQwGWrvCgQRu2RBeRTW80QsktOwAS6T4ECW71jAVS670c2lVdN1ZQuAyRN/oYujBXTg+h3ZsXH3LCuodA5A4D3OVkOUFGYF6sQ7Eg97w05IOgP0Cd+rVtWwPLR9Fxy5NhxzHcljS2Y=,iv:3bHsJ/d6vDzKHaZR1ZNF3Q+x81nPmUsGcFvssPu5qUI=,tag:RZVf/+LJZZ3AtrQYfl+CjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
