{{- if .Values.oauth2-proxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}-oauth2
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "oauth2-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  client-secret: {{ .Values.config.clientSecret | toString | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}-cookie
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "oauth2-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  cookie-secret: {{ .Values.config.cookieSecret | toString | b64enc | quote }}
{{- end }}
