#ENC[AES256_GCM,data:H8OFFANs+QtxxrBxw+JXLIL+jw7l5LQQ7YRVsVDhtj9QQ0WamoNC1l07zXGTLjBRcEPu0ilG3e3gXz0VEOLEMVNtng==,iv:2dJUx2bou3Q+W0y16SNWgsku1PMsvdQfogxDEPi0+S0=,tag:1SIJynAM7Z3O8tbx4OhQNw==,type:comment]
#ENC[AES256_GCM,data:Nyt7gVW+QtN11rL31rFLYn52mG7Yp55qv/LkbZV/9nNQ+Ds4iiYOl+HF+BXqLQo4xNgzYdgB+yZnXVTfeDx5W+tb,iv:EcXTr1XinxqtUj2aU0LBY58CCgMkfNB/d7/6T5d3Phs=,tag:Q/pynJwoVRPByaSy2Jb3Kw==,type:comment]
#ENC[AES256_GCM,data:apy4XY9gSl8wkkuYF1PrMv9veurowvUpLVHa3sHw,iv:aSmS+QXECAk5sREdrkvATlmccMxYqMPP5+kU4VepfLo=,tag:c6aH8AZlxHTnqR4bytTDtQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:S+8=,iv:yVe+zaZhuh+shjfBmSCB0+ItX4Z+rGo36N0tLlgsBbI=,tag:SvA6hfCcdJMlI7l7NrsPIg==,type:str]
kind: ENC[AES256_GCM,data:QYPH2Qnf,iv:pC3VobL5NrYgSlJoOE1fRprupnfHUYKVKDsHluw1vkI=,tag:lUC8fCA/6Ywk0wM365TisQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2Cd1ZAeM4XNNO3njPFr64PJv3lU=,iv:3oCiz3EI3D/wdsfIFippz91Z8/vZLtB8pGUIet8F10E=,tag:Su0cZA7JzxnEXsbD2/qWig==,type:str]
    namespace: ENC[AES256_GCM,data:yU+L1ryUsNpufmZA,iv:Hc0l2Rv3GHEa10EIMgDIPdC01EBt6mWoWk56B6wXcCc=,tag:iPAdpuyhLT5tDy5FcRqftg==,type:str]
type: ENC[AES256_GCM,data:lp0c8GVD,iv:LRuaN8GfZBo3ZQO5NOzMP9+MfGmwx3pXhJ1X/Ajw5a0=,tag:R/SfGoPPOZoEZ0q2fCA+VQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:L77qyZR1YCdX90S3VK6Zb/M87eTkmM+2T08F9ypnL4YFid29bto6jNlU7gCNbTLa7dY7S2U=,iv:G0271+PW9AiAj6G5PKAgK+TBdgJwWbrXt10w/fWrpSY=,tag:pQbEV5my9uXjHm8Mi1FHYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbHU5a3FNN3FEYmJDYmZp
            Qkpuc1B3S1pleHJ4MEdhbW1iUHY1UG1FbGtjCmpDd2QwMFZaT3VhSHIyT3QrbUJL
            djJnUnc0ZHJEWUU1b1ZNWjN3TVlWVzQKLS0tIGJYbmRsZ3I4dmZsUEkxS0pwVnhy
            ZG5kRjNLaFhCa1Y0RGpOcWF3L3hWS2sKQynmwX/h4O17zcO2+SAsdFonQvUdKEtn
            2hQNQ5jmVNEsR/IIetRpw0MOAocs4qkxpOzJXywRRS+EhLrwUMfP9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lf53pymuyys7tl4t89v27q0dmfkdqg0mxme7z7cqh2vefx8naanqwvlhtx
    lastmodified: "2026-05-15T08:56:10Z"
    mac: ENC[AES256_GCM,data:ioIXL6Fn/RKUEAyhSudk5YYbSZ/zXMJRHjqM8uDv/FVdM6VkqCwbHDQ2MhJMBR8K9ZxW5a4v5X0DACPQNukmF/w6RrC6ZGtfEUTPqzgVvFCBOUPZ2fEtJ+zNUD8Z0jQxRhWi0jb6HNzpfpo2AUj76asAzS/df/oF3E78WlssK+U=,iv:Z/lcfqYq6fdU20TJOBQcwmh+ETR5Ho8qgOZM+vPvwRA=,tag:/3SPYYFVOpP/8mBWM6VixQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
