{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus.grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.grafana.auth.adminPassword }}
  admin-password: {{ .Values.grafana.auth.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.grafana.ldap.bindPassword }}
  ldap-password: {{ .Values.grafana.ldap.bindPassword | b64enc | quote }}
  {{- else }}
  ldap-password: ""
  {{- end }}
{{- end }}
