---
{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.prometheus.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  {{- with .Values.prometheus.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.prometheus.service.type }}
  {{- if .Values.prometheus.service.sessionAffinity }}
  sessionAffinity: {{ .Values.prometheus.service.sessionAffinity }}
  {{- end }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}
