---
- name: Deploy Cilium CNI with SSO Network Preparation
  hosts: localhost
  gather_facts: no
  vars:
    cilium_namespace: "kube-system"
    verbose_mode: true

  tasks:
    - name: Set default deployment phase if not specified
      set_fact:
        cilium_deployment_phase: "{{ cilium_deployment_phase | default('full') }}"

    - name: Display deployment phase
      debug:
        msg: "Deploying Cilium in {{ cilium_deployment_phase }} mode"

    # PHASE 1: Network Preparation (run BEFORE Authentik)
    - name: "NETWORK PREPARATION: Deploy basic Cilium CNI"
      block:
        - name: Add Cilium Helm repository
          kubernetes.core.helm_repository:
            name: cilium
            repo_url: https://helm.cilium.io/
          vars:
            ansible_python_interpreter: "../.venv/bin/python"
          environment:
            PYTHONPATH: "../.venv/lib/python3.12/site-packages"

        - name: Create identity namespace with proper labels
          kubernetes.core.k8s:
            definition:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: identity
                labels:
                  name: identity
                  purpose: sso-services
                  network-policy: enabled
          vars:
            ansible_python_interpreter: "../.venv/bin/python"
          environment:
            PYTHONPATH: "../.venv/lib/python3.12/site-packages"

        - name: Deploy basic Cilium CNI (network preparation phase)
          kubernetes.core.helm:
            name: cilium
            chart_ref: cilium/cilium
            release_namespace: "{{ cilium_namespace }}"
            create_namespace: true
            values:
              # Basic CNI configuration for network preparation
              operator:
                replicas: 1
              ipam:
                mode: kubernetes
              kubeProxyReplacement: true
              k8sServiceHost: 127.0.0.1
              k8sServicePort: 6443
              
              # Enable service mesh features for SSO preparation
              serviceMesh:
                enabled: true
              l7Proxy: true
              
              # Enable network policy support
              policyEnforcement: default
              
              # Basic Hubble configuration (will be enhanced later)
              hubble:
                enabled: true
                relay:
                  enabled: true
                  resources:
                    requests:
                      cpu: 50m
                      memory: 64Mi
                    limits:
                      cpu: 200m
                      memory: 256Mi
                ui:
                  enabled: false  # Will be enabled in SSO integration phase
                  
              # Resource configuration for preparation phase
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
          vars:
            ansible_python_interpreter: "../.venv/bin/python"
          environment:
            PYTHONPATH: "../.venv/lib/python3.12/site-packages"

        - name: Wait for Cilium basic deployment
          shell: |
            echo "Waiting for Cilium pods to be ready..."
            kubectl -n {{ cilium_namespace }} wait --for=condition=ready pod -l k8s-app=cilium --timeout=300s
            echo "Cilium pods are ready!"
          register: cilium_wait_result

        - name: Verify basic Cilium network functionality
          shell: |
            echo "=== VERIFYING BASIC CILIUM NETWORK ==="
            
            # Check Cilium pod status
            kubectl -n {{ cilium_namespace }} get pods -l k8s-app=cilium
            
            # Wait for Cilium to be ready
            kubectl -n {{ cilium_namespace }} wait --for=condition=ready pod -l k8s-app=cilium --timeout=120s
            
            # Check Cilium status
            kubectl -n {{ cilium_namespace }} exec ds/cilium -- cilium status --brief || true
            
            echo "✓ Basic Cilium network is operational"
          register: basic_network_status
          retries: 3
          delay: 10
          until: basic_network_status.rc == 0

      when: cilium_deployment_phase in ['preparation', 'full']
      tags: [preparation, network]

    - name: Display deployment summary
      debug:
        msg:
          - "=== CILIUM DEPLOYMENT SUMMARY ==="
          - "Cilium deployed in {{ cilium_deployment_phase }} mode to namespace: {{ cilium_namespace }}"
          - "{% if cilium_deployment_phase in ['preparation', 'full'] %}Network preparation: Complete{% endif %}"
          - "{% if cilium_deployment_phase in ['sso-integration', 'full'] %}SSO integration: Complete{% endif %}"
          - "Basic network policy enforcement enabled"
          - "Ready for application deployment"
