# Traefik Middlewares for NOAH Infrastructure
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik-cors
  namespace: identity
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - POST
      - OPTIONS
    accessControlAllowHeaders:
      - "Authorization"
      - "Content-Type"
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 100
    addVaryHeader: true

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hubble-auth
  namespace: kube-system
spec:
  forwardAuth:
    address: "https://auth.noah-infra.com/outpost.goauthentik.io/auth/traefik"
    authResponseHeaders:
      - "Set-Cookie"
      - "X-authentik-username"
      - "X-authentik-groups"
      - "X-authentik-email"
      - "X-authentik-name"
      - "X-authentik-uid"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hubble-security
  namespace: kube-system
spec:
  headers:
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "same-origin"
    customRequestHeaders:
      X-Forwarded-Proto: "https"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ssl-redirect
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true
