apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nextcloud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-nextcloud-security@kubernetescrd
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.nextcloud.host }}
      secretName: {{ include "nextcloud.fullname" . }}-tls
  rules:
    - host: {{ .Values.nextcloud.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nextcloud.fullname" . }}
                port:
                  number: 8080
