---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nextcloud.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.autoscaling.enabled }}
  minAvailable: 1
  {{- else }}
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
