{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.fullname" . }}-data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.data.size | quote }}
  {{- if include "nextcloud.storageClass" . }}
  storageClassName: {{ include "nextcloud.storageClass" . }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.config.size | quote }}
  {{- if include "nextcloud.storageClass" . }}
  storageClassName: {{ include "nextcloud.storageClass" . }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.fullname" . }}-apps
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.apps.size | quote }}
  {{- if include "nextcloud.storageClass" . }}
  storageClassName: {{ include "nextcloud.storageClass" . }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.fullname" . }}-themes
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.themes.size | quote }}
  {{- if include "nextcloud.storageClass" . }}
  storageClassName: {{ include "nextcloud.storageClass" . }}
  {{- end }}
{{- end }}
