{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nextcloud.fullname" . }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /ocs/v2.php/apps/serverinfo/api/v1/info
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      honorLabels: true
      params:
        format: ['prometheus']
      headers:
        OCS-APIRequest: 'true'
        Authorization: 'Bearer YOUR_NEXTCLOUD_TOKEN'  # This should be set via secret
{{- end }}
