---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openedr
  labels:
    app: openedr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: openedr
  template:
    metadata:
      labels:
        app: openedr
    spec:
      containers:
        - name: openedr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8443
