apiVersion: v2
name: samba4
description: Samba4 Active Directory Domain Controller for NOAH
type: application
version: 0.0.1
appVersion: "4.19.0"
keywords:
  - samba4
  - active-directory
  - ldap
  - kerberos
maintainers:
  - name: NOAH Team
    email: admin@noah.local
