{{- if .Values.config.oidc.clientID }}
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientID: {{ .Values.config.oidc.clientID | quote }}
  clientSecret: {{ .Values.config.oidc.clientSecret | quote }}
  issuerURL: {{ .Values.config.oidc.issuerURL | quote }}
{{- end }}
