---
- name: reload sysctl
  command: sysctl --system

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload noah nat
  command: /usr/sbin/nft -f /etc/nftables.d/noah-garage-nat.nft
